### ISSUE TITLE
[variable-name] with ban-keywords converted to deprecated ban-keywords instead of new id-denylist

### ISSUE THREAD

**Issue by yrtimiD** [typescript-eslint/tslint-to-eslint-config#1028]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.3.0
-   ESLint version: 7.24.0

#### Actual Behavior
```json
"variable-name": [
  true,
  "ban-keywords"
]
```
is converted to 
```json
"id-blacklist": [
  "error",
  "any",
  "Number",
  "number",
  "String",
  "string",
  "Boolean",
  "boolean",
  "Undefined",
  "undefined"
]
```
#### Expected Behavior
id-blacklist was deprecated in favor of id-denylist since ESLint 7.4.0

```json
"id-denylist": [
  "error",
  "any",
  "Number",
  "number",
  "String",
  "string",
  "Boolean",
  "boolean",
  "Undefined",
  "undefined"
]
```
should be simple rename, code is same

**Comment by JoshuaKGoldberg** [comment]
Love it, thanks for the report @yrtimiD! Agreed this would be a great first issue to tackle for someone.

**Comment by hyperupcall** [comment]
It looks like #1221 fixes this

**Comment by JoshuaKGoldberg** [comment]
Ah good point, thanks for the spot!
