### ISSUE TITLE
Add missing ngrx rule converters

### ISSUE THREAD

**Issue by KingDarBoja** [typescript-eslint/tslint-to-eslint-config#1056]
#### Existing Behavior

There is another TSLint plugin that needs converting to the existing ESLint equivalent for the ngrx library:

- [ngrx-tslint-rules](https://github.com/timdeschryver/ngrx-tslint-rules)
- [eslint-plugin-ngrx](https://github.com/timdeschryver/eslint-plugin-ngrx)

We can use the [migration guide](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/migrating-from-ngrx-tslint-rules.md) provided at the eslint plugin docs.

#### Change Proposal

Add the missing converters. Should be easy to setup after adding #813 feature as most rules do not require configuration.

**Comment by rafaelss95** [comment]
I'm interested on taking this, @JoshuaKGoldberg @KingDarBoja (of course, if you haven't started working on this). Let me know if I can and another question: do you prefer a PR for each rule or can be everything in a single go?

**Comment by JoshuaKGoldberg** [comment]
🎉 , absolutely, please do take it on!

Since this repository has even fairly stable lately I'll leave that up to you. In theory one PR per rule would be easier for getting them in sooner and I generally lean towards that, but if you strongly prefer one big one that's fine too.

**Comment by rafaelss95** [comment]
Done, @JoshuaKGoldberg 🚀
