### ISSUE TITLE
Don't bother with a rule merger if rule arguments are the same

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#1086]
### Overview

As noted in #1085: some community rulesets have overlapping rules to others with the same output ESLint rules: e.g. both `convertAdjacentOverloadSignatures` and `convertConsecutiveOverloads` outputting `@typescript-eslint/adjacent-overload-signatures`.

#### Actual Behavior

A rule merger will be requested the second+ time an ESLint rule is seen in a converter's output: even if it outputs the same rule arguments as the ESLint rule's previously output rule arguments.

#### Expected Behavior

A rule merger should only be called for if an ESLint's rules are seen a second+ time _with new rule arguments_.

**Comment by Res42** [comment]
I'll do it.
