### ISSUE TITLE
Recommend npm or yarn installation commands for packages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#11]
When an ESLint configuration file is generated, at least the following packages will likely need to be available to use it:
* `eslint` itself
* `@typescript-eslint/*` plugins
* Any other plugins extended from by the package, such as `eslint-plugin-prettier`

When this package is run successfully, there should be a _(bright cyan?)_ recommendation for a shell command to install the requisite packages. It should use `npm` by default, or `yarn` if there is a `yarn.lock`.

**Comment by KingDarBoja** [comment]
Is possible to provide the user prompt to pick up an option to install all suggested packages based on `npm` | `yarn` | `no` options?

**Comment by JoshuaKGoldberg** [comment]
@KingDarBoja yup, that sounds great!

**Comment by beenotung** [comment]
It would be nice to add an option for `pnpm` beside `npm` and `yarn` :)
