### ISSUE TITLE
No such file or directory for tslint.json with 2.7.0

### ISSUE THREAD

**Issue by KyDenZ** [typescript-eslint/tslint-to-eslint-config#1159]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.7.0
-   ESLint version: N/A
-   Node version: 12.6.3

#### Actual Behavior

Tslint file not found with 2.7.0 version

#### Expected Behavior

I tested with version 2.6.0 it works

#### Reproduction

install tslint-to-eslint-config with 2.7.0 version, create a tslint.json file, run the command

**Comment by JoshuaKGoldberg** [comment]
Well, darn. Sorry about this @KyDenZ, and thank you for filing an issue on tslint-to-eslint-config!

I'll post more details in https://github.com/angular-eslint/angular-eslint/issues/571; in the meantime, I've released a **2.9.0** version that _should_ have the two suspicious changes from 2.7.0 reverted.

fyi @JamesHenry
