### ISSUE TITLE
Investigate merging notices

### ISSUE THREAD

**Issue by egiurleo** [typescript-eslint/tslint-to-eslint-config#119]
In #87, `tslint-to-eslint-config` began logging rule notices, but there wasn't any infrastructure that took into account the possibility of having to merge notices. I have updated line 81 in `convertRules.ts` to just merge the two notice arrays, but we should investigate creating a merger for rule notices.

**Comment by JoshuaKGoldberg** [comment]
I'm curious if there are any opinions on the best way to do this. One suggestion that pops to mind is to change rule mergers to have 1-2 members: `merger.ruleArguments` and an optional `merger.notices`.

**Comment by JoshuaKGoldberg** [comment]
On second thought, rule notices are pretty much always simple strings such as `"Class expressions will no longer be ignored."`. I think it's fine to just deduplicate strings and return the result:

```ts
Array.from(new Set(ruleOne.notices, ruleTwo.notices))
```

FYI @egiurleo - now accepting PRs! 😉

**Comment by egiurleo** [comment]
@JoshuaKGoldberg ;D ;D

**Comment by egiurleo** [comment]
I will look at this this week!

**Comment by JoshuaKGoldberg** [comment]
Released in `0.2.4`! ✨
