### ISSUE TITLE
> Dont worry be happy!

### ISSUE THREAD

**Issue by josepino147** [typescript-eslint/tslint-to-eslint-config#1266]
> Dont worry be happy!

Thanks. I'm happy now! 😁

_Originally posted by @RyanNerd in https://github.com/typescript-eslint/tslint-to-eslint-config/issues/1243#issuecomment-967287968_

**Comment by JoshuaKGoldberg** [comment]
Same. ❤️

**Comment by JoshuaKGoldberg** [comment]
Closing as resolved 😄

**Comment by kahlan88** [comment]
Is it resolved? I just ran the package (fresh install) on a project and got the same issue.

Am I missing something?
