### ISSUE TITLE
Re-add a CI build integration to pull requests

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#130]
Since moving this from [JoshuaKGoldberg](https://github.com/JoshuaKGoldberg) to [typescript-eslint](https://github.com/typescript-eslint/), there hasn't been a CI integration such as CircleCI or Azure Pipelines. There used to be a CircleCI integration set up
* CircleCI: I don't have permissions to set it up on this repository
* Pipelines: looks like [caching is still experimental](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops), so builds wouldn't be as snazzy as they were on CircleCI

FYI @JamesHenry - any chance we could stick on Circle? 🕺

**Comment by JamesHenry** [comment]
Hey @JoshuaKGoldberg I made you an admin of the repo, hopefully that gets you what you need?

**Comment by JoshuaKGoldberg** [comment]
Thanks! It's working on CircleCI. https://circleci.com/gh/typescript-eslint/tslint-to-eslint-config/tree/master

I don't see why it's not showing up in PRs as an integration, so I'll wait a bit before investigating...
