### ISSUE TITLE
Automatic vscode settings migration

### ISSUE THREAD

**Issue by nicojs** [typescript-eslint/tslint-to-eslint-config#133]
> why you no .vscode settings? 😒

### 🚀 Feature Request

It would be awesome if this tool could migrate .vscode settings from tslint to eslint. For example:

Change this:

```js
"editor.codeActionsOnSave": {
    "source.fixAll.tslint": true
}
```

To:

```js
"eslint.autoFixOnSave": true
```

Vscode settings can reside in either `.vscode/settings.json` or a `*.vscode-workspace` file.

#### Existing Behavior

No vscode support, bro. 🥺

#### Change Proposal

Probably this should be under a compiler flag.

Also, thanks for this awesome tool 👏, I will check it out later when I have some time.

**Comment by JoshuaKGoldberg** [comment]
Strongly agreed with this use case. Here's a rough proposal:
* Add CLI option to specify an editor config path, and have it default to `./vscode/settings.json`
* Rename the method passed to `runCli.ts` to `convertConfigs` _(plural)_
* Write that new `convertConfigs` that does both the existing `convertLintConfig` work and `convertEditorConfig`

`--editor`, perhaps? 

I'd like to keep the logic here editor-agnostic to users, so after this is done, we can file a followup issue for Atom support. :atom:

**Comment by nicojs** [comment]
Wait, there are other editors? 😨  

I hope to find some time soon, but I'm usually swamped... Whoever invented the 24h day?

**Comment by devinmotion** [comment]
@JoshuaKGoldberg I'll give it a try tomorrow. Looks like a nice task to implement while keeping everything clean in the code base.

**Comment by devinmotion** [comment]
@JoshuaKGoldberg @nicojs I started working on this with WIP-PR (https://github.com/typescript-eslint/tslint-to-eslint-config/pull/250). It was quite hard for me to fit into the existing structure and using this kind of DI ;) However finally I got a first version into working. There are still some things left (see TODOs).

Maybe you should have a look at it first if this approach would suite your needs?

**Comment by JoshuaKGoldberg** [comment]
> It was quite hard for me to fit into the existing structure and using this kind of DI ;) 

Ahh, yes, welcome to the light side. It takes a bit to get used to 😝
