### ISSUE TITLE
Missing mergers: no-caller, no-eval

### ISSUE THREAD

**Issue by joeyj-msft** [typescript-eslint/tslint-to-eslint-config#135]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: dunno. used npx to run
-   ESLint version: 5.16.0
-   Node version: 8.16.0

#### Actual Behavior

my eslint config is not updated

**console output**
✨ 101 rules replaced with their ESLint equivalents. ✨
📢 4 ESLint rules behave differently from their TSLint counterparts: 📢
* no-invalid-this:
  - Functions in methods will no longer be ignored.
* one-var:
  - Variables declared in for loops will no longer be checked.
* no-plusplus:
  - ++ and -- operators will now only be allowed in for loops.
* class-methods-use-this:
  - allow-protected methods will no longer be ignored.
💀 2 errors thrown. 💀
Check ./tslint-to-eslint-config.log for details.
️👀 132 rules do not yet have ESLint equivalents; defaulting to eslint-plugin-tslint. 👀
✅ All is well! ✅

**log file**
no-eval threw an error during conversion: Error: No merger for multiple output no-eval rule configurations.
    at exports.convertRules (...\npm-cache\_npx\14132\node_modules\tslint-to-eslint-config\src\rules\convertRules.js:37:67)
    at exports.convertConfig (...\npm-cache\_npx\14132\node_modules\tslint-to-eslint-config\src\conversion\convertConfig.js:15:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
no-arg threw an error during conversion: Error: No merger for multiple output no-caller rule configurations.
    at exports.convertRules (...\npm-cache\_npx\14132\node_modules\tslint-to-eslint-config\src\rules\convertRules.js:37:67)
    at exports.convertConfig (...\npm-cache\_npx\14132\node_modules\tslint-to-eslint-config\src\conversion\convertConfig.js:15:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

#### Expected Behavior

eslint config would be updated

#### Reproduction

Can you reply to this issue and let me know how much help you need to repro? I'd prefer not to just copy config/details from an internal repo.

**Comment by joeyj-msft** [comment]
This was actually changing my eslint config and the errors were non-blocking :)

**Comment by JoshuaKGoldberg** [comment]
Oh hi again @joeyj-msft! I'm going to re-open this issue because it's still a bug I'd like to fix. 😄 thanks for reporting!

Let's assume 0.2.2 as the version.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-mergers describes the root issue here. There are multiple instances of the `no-eval` and `no-callee` rules being output, so there needs to be a Merger in code created to handle that.

**Comment by joeyj-msft** [comment]
@JoshuaKGoldberg I'm wondering if this could generically handle merging the configs: https://lodash.com/docs/4.17.15#merge

**Comment by JoshuaKGoldberg** [comment]
Ah, I'd rather avoid using `merge` or other forms of generic object merging. There might be rules -either in the core ruleset or some contributed ones- where merging isn't as clean and simple as that. For now, let's be careful and have unfortunately explicit logic per rule.

**Comment by joeyj-msft** [comment]
Makes sense. How about an interim approach at outputting the conflicting rules in the log? I'd be happy to take a look at that as the merge will get painful to implement for each case

**Comment by JoshuaKGoldberg** [comment]
Interesting point. I agree, and that's what it's _supposed_ to be now! 😆Great observation.

Problem: this is being reported as an error with a full stack. Filed #143 to improve the error UX.

Let's keep this issue, #135, for adding in the missing merger.
