### ISSUE TITLE
CircleCi / Pipelines not set up for external PRs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#138]
FYI @JamesHenry - I don't have permissions on CircleCI or Azure Pipelines to set up builds on the typescript-eslint organization. Are you able to get that set up? If not, I'm ok with transferring back to my personal organization on GitHub to make it easier.

At this point, I'm up for either CircleCI or Pipelines, though I do have a preference for CircleCI. 😄 

Edit: by the way, I'm trying to access https://dev.azure.com/typescript-eslint/ with diogenesthecynic@hotmail.com as a login.

**Comment by JamesHenry** [comment]
This should now be enable on Circle, please let me know

**Comment by JoshuaKGoldberg** [comment]
🚀, it works! Thank you!
![build pipelines running in order](https://user-images.githubusercontent.com/3335181/62622593-b467b980-b8ec-11e9-94bd-f1a10771a03e.png)
