### ISSUE TITLE
react/jsx-curly-spacing merger error

### ISSUE THREAD

**Issue by natesulat** [typescript-eslint/tslint-to-eslint-config#1437]
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 2.12.3
-   ESLint version: ^8.12.0

#### CLI Output

```
❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.
```

#### File Output

```
Error: multiple output react/jsx-curly-spacing ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md. Thanks!
```

#### Reproduction

1. Check out https://github.com/kiva/protocol-common/tree/c8d881075030f8fd4e7f98558272b81698ed3eb2
2. `npx tslint-to-eslint-config`
3. ....?
4. Profit

**Comment by natesulat** [comment]
Just want to add that this is not at all urgent, but the Terminal told me to file a ticket, and far be it from me to refuse the Terminal's wishes

**Comment by JoshuaKGoldberg** [comment]
Looks like this is actually a dup of #1243. Thanks for filing!

**Comment by natesulat** [comment]
Thank you for looking!
