### ISSUE TITLE
Script creates wrongly named file on Windows

### ISSUE THREAD

**Issue by Ionaru** [typescript-eslint/tslint-to-eslint-config#144]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.4
-   ESLint version: -
-   Node version: 12.3.1
-   Windows 10, ran command in powershell.

#### Actual Behavior

Running the command in a tslint project creates a `eslintrc.js` file.

#### Expected Behavior

Running the command in a tslint project creates a `.eslintrc.js` file. (Note the `.`)

#### Reproduction

1. Checkout https://github.com/Ionaru/steve
2. Run `npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment]
Hi @Ionaru, thanks for the report! This package was mostly developed on Windows, so it's amusing that it might be incorrect by default. 

[ESLint's `--init`](https://eslint.org/docs/user-guide/getting-started#configuration) creates an `eslintrc.js` file (no `.`) by default. Seems reasonable to change this package to match their preference.

Errata: `.eslintrc.js` should still be valid according to https://eslint.org/docs/user-guide/configuring. Agreed it's more annoying to deal with.

**Comment by Ionaru** [comment]
@JoshuaKGoldberg I'm not sure we understand each other correctly.

I just tested `npx eslint --init` and it generated a `.eslintrc.js` (with `.`) for me.
This is what I'd expect because the eslint docs also speak of `.eslintrc.*` files.

So I think this package needs to be changed so it also generates a `.eslintrc.js` (with `.`) file.

**Comment by JoshuaKGoldberg** [comment]
Ah sorry, gotcha! Yes, let's match the behavior of `eslint --init`.

Errata: looks like https://eslint.org/docs/user-guide/getting-started#configuration is actually out of date?

**Comment by akx** [comment]
This also happens on macOS.
