### ISSUE TITLE
Incorrectly generated space-before-function-paren

### ISSUE THREAD

**Issue by akx** [typescript-eslint/tslint-to-eslint-config#147]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.5
-   ESLint version: 6.2.2
-   Node version: 12.6

#### Actual Behavior

The tool generates a

 ```json
        "space-before-function-paren": [
            "error",
            {
                "anonymous": "never",
                "asyncArrow": "always",
                "constructor": "never",
                "method": "never",
                "named": "never",
            },
        ],
```

rule which does not validate when Eslint is starting:

```
	Configuration for rule "space-before-function-paren" is invalid:
	Value {"anonymous":"never","asyncArrow":"always","constructor":"never","method":"never","named":"never"} should be equal to one of the allowed values.
	Value {"anonymous":"never","asyncArrow":"always","constructor":"never","method":"never","named":"never"} should NOT have additional properties.
	Value {"anonymous":"never","asyncArrow":"always","constructor":"never","method":"never","named":"never"} should match exactly one schema in oneOf.
```

#### Expected Behavior

The rule is correctly generated according to [the spec](https://eslint.org/docs/rules/space-before-function-paren#options). It seems `method` and `constructor` shouldn't be there.

**Comment by Shubhamchinda** [comment]
Hey, Can I work on this issue?

**Comment by JoshuaKGoldberg** [comment]
😍 yes please, @Shubhamchinda! That'd be fantastic!

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operator.

**Comment by Shubhamchinda** [comment]
Hey @JoshuaKGoldberg, Do we need to make the changes in [file](https://github.com/eslint/eslint/blob/master/lib/rules/space-before-function-paren.js) ?

I also wanted to know how can I test the changes ?

Thanks a lot! :)

**Comment by JoshuaKGoldberg** [comment]
Do we need to make the changes in [file](https://github.com/eslint/eslint/blob/master/lib/rules/space-before-function-paren.js)? 

Not quite. That ESLint repository is the source of ESLint rules. This tslint-to-eslint-config repository is a separate description of how to convert TSLint rules' configurations to work with those rules. So there are three repositories:
* ESLint
* TSLint
* eslint-to-tslint-config

We're exclusively working within eslint-to-tslint-config. You'll want to look at:
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/b062d10ace13c239a247c391ff9a9e0b4a7c4d7f/src/rules/converters/space-before-function-paren.ts#L3.

> how can I test the changes ?

Unit tests for the `space-before-function-parent` converter exist here:
https://github.com/typescript-eslint/tslint-to-eslint-config/blob/b062d10ace13c239a247c391ff9a9e0b4a7c4d7f/src/rules/converters/tests/space-before-function-paren.test.ts#L3

This is a standard [Jest](https://jestjs.io) test setup, so running `jest space-before-function-parent` on the console will re-run tests. Add `--watch` to have them continuously re-run as you update files.

**Comment by Shubhamchinda** [comment]
Alright! I am doing this!
Thanks

**Comment by KingDarBoja** [comment]
Any updates on this? I got the same error while testing generated lint rules.

**Comment by JoshuaKGoldberg** [comment]
Ping @Shubhamchinda - still interested in this?

**Comment by ElkeBxl** [comment]
If @Shubhamchinda is not interested anymore, I'd happily take it over :)

**Comment by JoshuaKGoldberg** [comment]
Ping @ElkeBxl - still interested in this?
