### ISSUE TITLE
Conflict between tslint:align and @typescript-eslint/indent

### ISSUE THREAD

**Issue by rhysowen9** [typescript-eslint/tslint-to-eslint-config#149]
I'm running into a conflict between @typescript-eslint/indent and the align rule in @typescript-eslint/tslint/config, specifically with regard to the alignment of parameters on my class constructors.

### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.5
-   ESLint version: 6.3.0
-   Node version: 10.15.3

#### Actual Behavior

Expected indentation of x spaces but found x  @typescript-eslint/indent
or
parameters are not aligned (tslint:align)  @typescript-eslint/tslint/config

#### Expected Behavior

I don't really mind which convention is accepted as long as its consistent.

#### Reproduction

```ts
constructor(private router: Router,
            private authenticationService: AuthenticationService,
            private tokenService: TokenService) {}
```

```ts
constructor(private router: Router,
  private authenticationService: AuthenticationService,
  private tokenService: TokenService) { }
```

```JSON
{
    "rules": {
        "@typescript-eslint/indent": [
            "error",
            2
        ],
        "@typescript-eslint/tslint/config": [
            "error",
            {
                "rulesDirectory": [
                    "**MyPath**"
                ],
                "rules": {
                    "align": [
                        true,
                        "parameters",
                        "statements"
                    ]
                }
            }
        ]
    }
}
```

**Comment by JoshuaKGoldberg** [comment]
Thanks for the report @rhysowen9! It sounds like the `align` rule needs a converter that outputs the `indent` rule. Accepting PRs to add that in.

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operate.

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg I do think it is already fixed because I see the rule on the `converters` map.

**Comment by JoshuaKGoldberg** [comment]
@KingDarBoja the issue here is that TSLint's `align` rule isn't yet converted - not the `indent` one, sadly;.

**Comment by KingDarBoja** [comment]
> @KingDarBoja the issue here is that TSLint's `align` rule isn't yet converted - not the `indent` one, sadly.

I will look into it these days 🍰

**Comment by jeremyyap** [comment]
May I work on this? `typescript-eslint`'s `indent` rule supports an indentation level of `"first"` which should be similar to what TSLint's `align` rule enforces: 

> the string "first" indicating that all parameters of the declaration must be aligned with the first parameter
