### ISSUE TITLE
RulesDirectory using a relative path

### ISSUE THREAD

**Issue by Razzeee** [typescript-eslint/tslint-to-eslint-config#151]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: X.X.X current one used by NPX
-   ESLint version: X.X.X not installed yet
-   Node version: 10.16.3

#### Actual Behavior

`eslintrc.js` get's generated, but the `rulesDirectory` field in the `@typescript-eslint/tslint/config` object is using an absolute path.

#### Expected Behavior

It should be figuring out the relative path and be using this. As that's the only path, that will work on another PC.

#### Reproduction

Ran it against master of https://github.com/elm-tooling/elm-language-client-vscode but I don't think it's affected by the project in this case.

**Comment by JoshuaKGoldberg** [comment]
Agreed, thanks for filing this @Razzeee! Accepting PRs to make that change.

**Comment by KingDarBoja** [comment]
I tried to reproduce the issue but got no `rulesDirectory` on the `@typescript-eslint/tslint/config` object.

**Comment by Razzeee** [comment]
I think this is solved as this tool now seems to write `rules` instead.
