### ISSUE TITLE
Some removed rules are included in eslintrc.js

### ISSUE THREAD

**Issue by paibamboo** [typescript-eslint/tslint-to-eslint-config#153]
### 🐛 Bug Report
-   `tslint-to-eslint-config` version: 0.2.4
-   ESLint version: None
-   Node version: 10.10.0

#### Actual Behavior
`@typescript-eslint/no-triple-slash-reference`, `@typescript-eslint/prefer-interface`, `@typescript-eslint/no-object-literal-type-assertion`, and `@typescript-eslint/no-angle-bracket-type-assertion` are included in `eslintrc.js`

#### Expected Behavior
Those 4 rules should not be included since they are replaced by new rules since v 2.0.0. (See list of breaking changes [here](https://github.com/typescript-eslint/typescript-eslint/issues/501))
- `@typescript-eslint/prefer-interface` is replaced by `@typescript-eslint/consistent-type-definitions`.
- `@typescript-eslint/no-triple-slash-reference` is replaced by `@typescript-eslint/triple-slash-reference`
- `@typescript-eslint/no-object-literal-type-assertion` and `@typescript-eslint/no-angle-bracket-type-assertion` are combined in to one single rule `@typescript-eslint/consistent-type-assertions`

#### Reproduction
- Clone this [repo](https://github.com/crazyfactory/ts-react-boilerplate).
- Go to project dir
- Run `npm install`
- Run `npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment]
Yup, these should be replaced. Accepting PRs to fix converters!

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operate.

**Comment by KingDarBoja** [comment]
Hello @paibamboo,

I did a quick search on the official **typescript-eslint** GitHub and found these issues regarding the listed rules:

- `@typescript-eslint/prefer-interface` is indeed removed but there is nothin about replacement as stated on [#433](https://github.com/typescript-eslint/typescript-eslint/issues/433) and [this member comment](https://github.com/typescript-eslint/typescript-eslint/issues/651#issuecomment-506087652).
- `@typescript-eslint/no-triple-slash-reference` is indeed removed and replaced by `triple-slash-reference` as stated by the same member comment above.
- `@typescript-eslint/no-object-literal-type-assertion` was not replaced, it is one of the recommended ones _(check author issue on the same member comment)_.
- `@typescript-eslint/no-angle-bracket-type-assertion` has the same behaviour as above. Also, probably it is a side effect as happened on this [issue](https://github.com/typescript-eslint/typescript-eslint/issues/863).

**Comment by paibamboo** [comment]
HI @KingDarBoja, I added the breaking changes link in the post.

**Comment by KingDarBoja** [comment]
> HI @KingDarBoja, I added the breaking changes link in the post.

Thank you, now it makes sense for me. Surely those rules will be fixed as soon as possible 🍰
