### ISSUE TITLE
npx tslint-to-eslint-config not working

### ISSUE THREAD

**Issue by epsilonhalbe** [typescript-eslint/tslint-to-eslint-config#1536]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.13.1
-   Node version: 18.4.0 (osx M1), 16.15.1 (osx intel)

#### Actual Behavior

running `npx tslint-to-eslint-config -- --version` or any other command fails with `Cannot find module '../src/cli/main'` and indeed if I look into `~/.npm/_npx/ab091f4918e92575/node_modules/tslint-to-eslint-config/` there is no `src` folder.
but looking into `~/.npm/_npx/ab091f4918e92575/node_modules/tslint-to-eslint-config/bin/tslint-to-eslint-config` - it tries to access that.

#### Expected Behavior

program runs and converts tslint config file to eslint config

#### Reproduction

```bash
rm -rf ~/.npm/_npx/ab091f4918e92575/
npx tslint-to-eslint-config -- --version
```

**Comment by JoshuaKGoldberg** [comment]
Sorry about that folks! There's something funky going on with the automatic package publishing. I published `tslint-to-eslint-config@2.13.2` manually and it works.

```shell
npx tslint-to-eslint-config@2.13.2
```
