### ISSUE TITLE
Typescript-specific rules should be used instead of normal eslint rules

### ISSUE THREAD

**Issue by paibamboo** [typescript-eslint/tslint-to-eslint-config#154]
### 🐛 Bug Report
-   `tslint-to-eslint-config` version: 0.2.4
-   ESLint version: None
-   Node version: 10.10.0

#### Actual Behavior
`member-ordering` and `no-empty-function` are included in `eslintrc.js` instead of `@typescript-eslint/member-ordering` and `@typescript-eslint/no-empty-function`

#### Expected Behavior
`@typescript-eslint/member-ordering` and `@typescript-eslint/no-empty-function` should be used instead of `member-ordering` and `no-empty-function` respectively. Since people who are using this cli are using typescript anyway. It makes sense to use rules that handle typescript specific code.

#### Reproduction
- Clone this [repo](https://github.com/crazyfactory/ts-react-boilerplate).
- Go to project dir
- Run `npm install`
- Run `npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment]
Indeed, great observation @paibamboo! 🙌 Accepting PRs to replace references to the "vanilla" ESLint rules `member-ordering` and `no-empty-function` with their `@typescript-eslint/` equivalents.

**Comment by afonsojramos** [comment]
I can try to tackle this!
