### ISSUE TITLE
 tslint-to-eslint-config  >=2.0.0 Depends on vulnerable versions of json5

### ISSUE THREAD

**Issue by theengineer0101** [typescript-eslint/tslint-to-eslint-config#1664]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.13.3

#### Actual Behavior

It is flagged as Severity: high vulnerabilities in audit
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h

#### Expected Behavior

 Please update the current package dependence json5 package to json5@2.2.2, which is the patch version

#### Reproduction

Please run 'npm audit' on the latest npm package version.

**Comment by JoshuaKGoldberg** [comment]
👍 published `tslint-to-eslint-config@2.13.4`. Thanks for the report!

(the project's source had been upgraded to the newer version in #1652, just not released yet)
