### ISSUE TITLE
Missing converter: quotemark

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#182]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 1.2.0
-   `typescript-eslint` version: 2.3.2

#### TSLint Rule Name

`quotemark`

**Comment by JoshuaKGoldberg** [comment]
The issue here is that this package doesn't know how to convert the TSLint rule into the equivalent ESLint rule. Accepting PRs to add in a converter! 🙌 

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operate. Check the [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) to see suggestions on equivalent ESLint rules to convert to.

See #189 for an example of a simple rule converter that was recently added in.

**Comment by mauricetmeyer** [comment]
I'd like to take on this one.
