### ISSUE TITLE
Missing converter: strict-boolean-expressions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#185]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 1.2.0
-   `typescript-eslint` version: 2.3.2

#### TSLint Rule Name

`strict-boolean-expressions`

**Comment by JoshuaKGoldberg** [comment]
The issue here is that this package doesn't know how to convert the TSLint rule into the equivalent ESLint rule. Accepting PRs to add in a converter! 🙌 

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operate. Check the [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) to see suggestions on equivalent ESLint rules to convert to.

See #189 for an example of a simple rule converter that was recently added in.

**Comment by KingDarBoja** [comment]
Hello! I have no idea why the referenced PR was closed but if this issue isn't being fixed for someone else, I am available to fix this one 🍰 

But I am pretty sure the referenced PR was okay, so probably gonna copy & paste it if there is no problem with that.

Cheers!

**Comment by JoshuaKGoldberg** [comment]
Yeah, @208 looked good at first glance, but there might be some subtle differences in rule options? Any differences can be explained in `notices` 🤷‍♂. 

FYI @exw.

**Comment by KingDarBoja** [comment]
> Yeah, @208 looked good at first glance, but there might be some subtle differences in rule options? Any differences can be explained in `notices` 🤷‍♂.
> 
> FYI @exw.

Okay, making a PR from it after checking the rule options. By the way, you tagged a user by using the `@` instead of the `#` 😆
