### ISSUE TITLE
Missing converter: trailing-comma

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#186]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 1.2.0
-   `typescript-eslint` version: 2.3.2

#### TSLint Rule Name

`trailing-comma`

**Comment by JoshuaKGoldberg** [comment]
The issue here is that this package doesn't know how to convert the TSLint rule into the equivalent ESLint rule. Accepting PRs to add in a converter! 🙌 

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters) talks about how these converters operate. Check the [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) to see suggestions on equivalent ESLint rules to convert to.

See #189 for an example of a simple rule converter that was recently added in.

**Comment by JoshuaKGoldberg** [comment]
Go ahead @deerawan! ✨

**Comment by deerawan** [comment]
@JoshuaKGoldberg I found some variations of TSLint options to be mapped to ESLint one 

e.g
```js
{"multiline": "always", "singleline": "never"} // tslint
“always-multiline” // eslint

{ “multiline”: “always”, “singleline”: “always” } // tslint
“always” // eslint

{ “multiline”: “never”, “singleline”: “never” } // tslint
"never" // eslint

{"multiline": "always", "singleline": { “arrays”: “always-multiline” }} // tslint
..... // eslint

and much more
```
How far do you think we should handle these cases?

**Comment by JoshuaKGoldberg** [comment]
Sorry @deerawan, I don't quite follow what you're asking?

In general, I think we should aim to get the closest possible mapping of equivalent behaviors... and if it's impossible to get them exactly the same, `notices` to explain the differences.

**Comment by KingDarBoja** [comment]
I could go ahead and fix this one if @deerawan is not working on this 🍰

**Comment by deerawan** [comment]
@KingDarBoja almost finish with it 👍
