### ISSUE TITLE
Is something wrong in end-to-end test configuration?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#225]
There were a few reports in recent PRs that end-to-end tests aren't quite working. #216 should fix most or all of the issues, but I'd like to audit them again to check.

**Comment by JoshuaKGoldberg** [comment]
Relevant: https://github.com/typescript-eslint/tslint-to-eslint-config/pull/209#discussion_r331774174

**Comment by JoshuaKGoldberg** [comment]
https://circleci.com/gh/typescript-eslint/tslint-to-eslint-config/1961?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link shows that `"settings"` are read from the existing ESLint files... but I don't see where they're coming from. 😠

**Comment by JoshuaKGoldberg** [comment]
Per #217: I'm just going to delete these. The project is stable right now and the tests are frustrating & slow to deal with.

**Comment by KingDarBoja** [comment]
Well looks like sometimes it fails, sometimes it doesn't, but better to remove them if all other test suites are passing and coverage is 100%.
