### ISSUE TITLE
List of "rules do not yet have ESLint equivalents" is hard to find

### ISSUE THREAD

**Issue by HolgerJeromin** [typescript-eslint/tslint-to-eslint-config#233]
### 🚀 Feature Request
The console output `? 1 ESLint rule behaves differently from their TSLint counterparts: ?` has a listing about all the rules with problems: ` * no-invalid-this:` for example.
So it is surprising that the part `5 rules do not yet have ESLint equivalents` does not list the rules here, too.
I think the easiest way (with not too much console output) is to add an hint about the log in current directory. 

#### Existing Behavior

````
? 25 rules replaced with their ESLint equivalents. ?
? 1 ESLint rule behaves differently from their TSLint counterparts: ?
* no-invalid-this:
  - Functions in methods will no longer be ignored.
?? 5 rules do not yet have ESLint equivalents; defaulting to eslint-plugin-tslint. ?
? All is well! ?
````
Which 5 rules? I needed a few minutes to check if there is a log.
#### Change Proposal

````
? 25 rules replaced with their ESLint equivalents. ?
? 1 ESLint rule behaves differently from their TSLint counterparts: ?
* no-invalid-this:
  - Functions in methods will no longer be ignored.
?? 5 rules do not yet have ESLint equivalents (see generated log file); defaulting to eslint-plugin-tslint for this rules. 
? All is well! ?
````

**Comment by HolgerJeromin** [comment]
Oh, I just found "the list" in `"@typescript-eslint/tslint/config"` property of the generated config. 
My feeling was that `tslint-to-eslint` would reduce my tslint.json  to the remaining task or something like that.

**Comment by JoshuaKGoldberg** [comment]
@HolgerJeromin this is a great issue, thanks for filing it! I see there as being two possible improvements to be made:

* Mention more specifically where those 5 rules without equivalents are listed
* Provide a CLI option to shrink your `tslint.json` file instead of using the `tslint/config` property

...additionally, I think it'd be separately useful to have a `.md` file somewhere in this repo's docs that has a table of rules with whether they've been converted, similar to https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md.

Thoughts?

**Comment by HolgerJeromin** [comment]
> Mention more specifically where those 5 rules without equivalents are listed

See my proposal. My wording `defaulting to eslint-plugin-tslint for these rules.` seems important, so it is clear that tslint stuff is reduced. Which was not in my head.

> Provide a CLI option to shrink your tslint.json file instead of using the tslint/config property

After finding the list in `tslint/config` I find this way very good. Moving legacy tslint entries to eslint entries is done in one file. So please keep it that way. 
Perhaps the tslint property could be moved up in the file. While learning eslint config I read from top to bottom, so found the legacy stuff later. Having the legacy tslint stuff above the eslint entries would be easier to understand for me.

> .additionally, I think it'd be separately useful to have a .md file somewhere in this repo's docs that has a table of rules with whether they've been converted

Not bad, but for me the mentioned ROADMAP was sufficient.

**Comment by KingDarBoja** [comment]
A idea just came to my mind for listing the rules that do not yet have ESLint equivalents: Use [console.table API](https://nodejs.org/docs/latest-v10.x/api/console.html#console_console_table_tabulardata_properties), which is available since Node.JS v10.0.0.

Thoughts?

**Comment by JoshuaKGoldberg** [comment]
Thought about this a bit - I think now that the CLI output is more clear (as @HolgerJeromin mentioned & improved), there's not much more actionable here. A [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) already exists in eslint-plugin that shows rule equivalents. Putting a visualization of that in the CLI, for example, is probably out of scope for what we really need to do.

Please do post here or open a new issue if you feel there's more to be addressed!
