### ISSUE TITLE
replace deprecated no-triple-slash-reference with triple-slash-reference

### ISSUE THREAD

**Issue by ThangHuuVu** [typescript-eslint/tslint-to-eslint-config#241]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.8
-   ESLint version: 6.5.1
-   Node version: 10.16.3

#### Actual Behavior

TSLint no-reference is being converted to
`"@typescript-eslint/no-triple-slash-reference"`
#### Expected Behavior

TSLint no-reference should be converted to
`"@typescript-eslint/triple-slash-reference"`
#### Reproduction

tslint.json file:
```
{
  "rules": [
    ...,
    "no-reference": true,
    ...
}
```
npx tslint-to-eslint-config

**Comment by KingDarBoja** [comment]
Looks like this one is part of several ESLint rules being covered by the same rule.

Checkout [triple-slash-reference](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/triple-slash-reference.md) and then search for `no-reference-import` at the [roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) and you will see what I am talking about.
