### ISSUE TITLE
Missing Converter: deprecation

### ISSUE THREAD

**Issue by MCluck90** [typescript-eslint/tslint-to-eslint-config#249]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 0.2.8
-   `typescript-eslint` version: 2.4.0

#### TSLint Rule Name

[`deprecation`](https://palantir.github.io/tslint/rules/deprecation/)

#### Package Source

TSLint core

**Comment by KingDarBoja** [comment]
Looks like this TSLint rule converter is missing, good thing it is a easy one as the equivalent ESLint [no-deprecated](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-deprecated.md) rule is being supported by `eslint-plugin-import`, whose behaviour is the same as the TSLint one.
