### ISSUE TITLE
Indent converter does not map options

### ISSUE THREAD

**Issue by jeremyyap** [typescript-eslint/tslint-to-eslint-config#251]
### 💥 Incomplete Converter

-   `tslint-to-eslint-config` version: 0.2.8
-   `typescript-eslint` version: 2.5.0

#### TSLint Rule Name

`indent` has a converter to `@typescript-eslint/indent` but it does not map the options over.

TSLint's [indent](https://palantir.github.io/tslint/rules/indent/) rule supports options of `tabs` or `spaces` and `2` or `4` indent width in the case of space indentation.

Sample TSLint config:

```
{
  "rules": {
    "indent": [ true, "spaces", 2 ]
  }
}
```

Expected output:
```
    "rules": {
        "@typescript-eslint/indent": [ "error", 2 ]
    }
```

Actual output:
```
    "rules": {
        "@typescript-eslint/indent": "error"
    }
```

**Comment by JoshuaKGoldberg** [comment]
Ha, I knew there was something about this... +1 to PRs that fix this!
