### ISSUE TITLE
Missing Merger:  @typescript-eslint/member-delimiter-style

### ISSUE THREAD

**Issue by evless** [typescript-eslint/tslint-to-eslint-config#254]
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 0.2.8
-   ESLint version: 6.5.1

#### CLI Output

![image](https://user-images.githubusercontent.com/10083505/67468140-aa836600-f652-11e9-9e27-6a3760f2ec3c.png)

#### File Output

```
Error: multiple output @typescript-eslint/member-delimiter-style ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏comment-format does not yet have an ESLint equivalent.
jsdoc-format does not yet have an ESLint equivalent.
jsx-key does not yet have an ESLint equivalent.
jsx-no-bind does not yet have an ESLint equivalent.
jsx-no-string-ref does not yet have an ESLint equivalent.
jsx-self-close does not yet have an ESLint equivalent.
no-reference-import does not yet have an ESLint equivalent.
prettier does not yet have an ESLint equivalent.
react-hooks-nesting does not yet have an ESLint equivalent.
readonly-array does not yet have an ESLint equivalent.
```

#### Reproduction

https://gist.github.com/evless/e395faa19b9f43098738ec25e36ee6f0

**Comment by JoshuaKGoldberg** [comment]
Thanks for this issue @evless! Accepting PRs to add the missing merger in. 

[`docs/Development.md`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Development.md) has a root overview for how to get started. Within that, [`docs/Architecture.md#rule-converters`](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-mergers) talks about how these mergers operate.
