### ISSUE TITLE
TypeError: [[rawConfiguration.extends],[reportedConfiguration.extends]].flat is not a function

### ISSUE THREAD

**Issue by bagage** [typescript-eslint/tslint-to-eslint-config#264]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.2.11
-   TSLint version: 5.18.0
-   ESLint version: none?
-   Node version: 10.17.0

#### Actual Behavior

1. I generated an empty angular project with `ng new`, `ng 8.1.3`.
2. I updated manually tslint from 5.15 to 5.18 since this is the minimum required version
3. Then I ran `npx tslint-to-eslint-config` and expected it to migrate from tslint to eslint

But I got this error:

```
npx: installed 41 in 3.972s
❌ 1 error running tslint-to-eslint: ❌
TypeError: [[rawConfiguration.extends],[reportedConfiguration.extends]].flat is not a function
    at exports.findTSLintConfiguration (/home/user/.npm/_npx/19151/lib/node_modules/tslint-to-eslint-config/src/input/findTSLintConfiguration.js:22:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Expected Behavior

I'd expected it to migrate to `eslint` smoothly.

#### Reproduction

`tslint-to-eslint-config` is empty.

**Comment by humodz** [comment]
Same issue, using node 10.16.0
A temporary workaround is adding the following lines to `node_modules/tslint-to-eslint-config/bin/tslint-to-eslint-config`, before the require:

```js
if (!Array.prototype.flat) {
    Object.defineProperty(Array.prototype, 'flat', {
        configurable: true,
        value: function flat () {
            var depth = isNaN(arguments[0]) ? 1 : Number(arguments[0]);

            return depth ? Array.prototype.reduce.call(this, function (acc, cur) {
                if (Array.isArray(cur)) {
                    acc.push.apply(acc, flat.call(cur, depth - 1));
                } else {
                    acc.push(cur);
                }

                return acc;
            }, []) : Array.prototype.slice.call(this);
        },
        writable: true
    });
}

if (!Object.prototype.fromEntries) {
    Object.defineProperty(Object.prototype, 'fromEntries', {
        configurable: true,
        writable: true,
        value: function fromEntries (iterable) {
            return [...iterable].reduce((obj, [key, val]) => {
                obj[key] = val
                return obj
            }, {})
        }
    })
}
```

**Comment by jeremyyap** [comment]
This should be the same issue as #260, only Node 12+ is supported as stated [here](https://github.com/typescript-eslint/tslint-to-eslint-config#usage).

**Comment by JoshuaKGoldberg** [comment]
Mmhh, if this is a common complaint then the package should support Node 10. I'll fix.

Thanks for reporting & discussing, folks!
