### ISSUE TITLE
Invalid "no-underscore-dangle" rule

### ISSUE THREAD

**Issue by devuxer** [typescript-eslint/tslint-to-eslint-config#266]
-   `tslint-to-eslint-config` version: 0.2.11
-   ESLint version: 6.6.0
-   Node version: 12.8.1

#### Actual Behavior

Converts to this:

```js
"no-underscore-dangle": [
    "error",
     "off"
],
```

Which generates this error:

> ..\.eslintrc.js: Configuration for rule "no-underscore-dangle" is invalid: Value "off" should be object.

#### Expected Behavior

Should convert to this:

    "no-underscore-dangle": "off",

#### Reproduction

Point to a tslint.json file with the following rule:

    "variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore"]

**Comment by JoshuaKGoldberg** [comment]
Good find, thanks for posting! Accepting PRs to fix this bug. 🚀

**Comment by dimabory** [comment]
@JoshuaKGoldberg Could you clarify a bit? Is it possible to replace TSLint severity to `off` while converting the rule? I'd like to take it over.

**Comment by dimabory** [comment]
@JoshuaKGoldberg Could you clarify please a bit? Is it possible to replace TSLint rule severity level while converting to ESLint rule? I'd like to take it over.
