### ISSUE TITLE
Output node 12 requirement if not met

### ISSUE THREAD

**Issue by moonray** [typescript-eslint/tslint-to-eslint-config#267]
### 🐛 Bug Report

When using an older version of node you are simply met by `Unexpected token {` and nothing else happens. It would be helpful if a node version check is done before execution and preemptively exit with a notice to upgrade node.

#### Actual Behavior

When using node 8 (for instance), the script aborts with `Unexpected token {`.

#### Expected Behavior

An elegant warning.

#### Reproduction

1. use node 8
2. run `npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment]
Hi @moonray! I actually think it would be better to just go ahead and support Node 8 😄. Thoughts?

**Comment by JoshuaKGoldberg** [comment]
Mmhh, yes, I'll just do that. 😄

**Comment by LaloHao** [comment]
Could we get the warning in the meantime? I had to search on issues to find this out (using `npx ...`)

**Comment by JoshuaKGoldberg** [comment]
Support for Node 8 is merged into master. I'll release a new version very soon (likely tonight). Sorry for the lack of clarity here! 😢

**Comment by JoshuaKGoldberg** [comment]
@LaloHao @moonray published as `0.3.0`! 🙌 

If that doesn't work on your Node version, would you mind either posting here or filing a new issue with the warning? Thanks!
