### ISSUE TITLE
Error missing merger running tslint-to-eslint-config

### ISSUE THREAD

**Issue by yannick007** [typescript-eslint/tslint-to-eslint-config#272]
### 💥 Missing Merger
    "tslint": "^5.20.1",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-react": "^4.1.0"
    "eslint": "^6.7.0",
    "eslint-plugin-react": "^7.16.0",
    "@typescript-eslint/eslint-plugin": "^2.8.0",
    "@typescript-eslint/parser": "^2.8.0",

#### CLI Output

npx: installed 54 in 7.575s
✨ 95 rules replaced with their ESLint equivalents. ✨
📢 8 ESLint rules behave differently from their TSLint counterparts: 📢
* camelcase:
  - Leading and trailing underscores (_) in variable names will now be ignored.
* no-underscore-dangle:
  - Leading or trailing underscores (_) on identifiers will now be forbidden.
* no-invalid-this:
  - Functions in methods will no longer be ignored.
* no-unused-expressions:
  - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
* prefer-arrow/prefer-arrow-functions:
  - ESLint does not support allowing standalone function declarations.
  - ESLint does not support allowing named functions defined with the function keyword.
* eqeqeq:
  - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
* no-redeclare:
  - ESLint does not support check-parameters.
* @typescript-eslint/space-within-parens:
  - The number of spaces will be ignored
💀 1 error thrown. 💀
Check ./tslint-to-eslint-config.log for details.
️👀 20 rules do not yet have ESLint equivalents (see generated log file); defaulting to eslint-plugin-tslint for these rules. 👀
⚡ 4 packages are required for new ESLint rules. ⚡
        no-null
        import
        prefer-arrow
        eslint-plugin-import
✅ All is well! ✅

#### File Output

multiple output @typescript-eslint/consistent-type-assertions ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.

#### Reproduction
have tslint configuration set up
then perform npx tslint-to-eslint-config

**Comment by JoshuaKGoldberg** [comment]
Hi @yannick007, thanks for filing this issue! 

Per the [missing mergers issue template](https://raw.githubusercontent.com/typescript-eslint/tslint-to-eslint-config/7b0ebdf703756a731f2ddbdf3461309b78dbf2ce/.github/ISSUE_TEMPLATE/missing_merger.md) just the output from `npx tslint-to-eslint-config` isn't enough to diagnose what's wrong. Please paste a link to a repository, Gist, or other means of reproducing your error here. Note that `tslint-to-eslint-config` includes information from `package.json`, `tsconfig.json`, and other files, so just your TSLint configuration may not be enough - but it's a start if that's all you have time for.

Closing this issue as non-actionable for now, but happy to re-open if with more info!
