### ISSUE TITLE
Missing converter: import-blacklist to no-restricted-imports

### ISSUE THREAD

**Issue by mc-suchecki** [typescript-eslint/tslint-to-eslint-config#277]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 0.3.1
-   `typescript-eslint` version: 2.10.0

#### TSLint Rule Name

import-blacklist

#### ESLint Rule Name

no-restricted-imports

#### Example

````
"import-blacklist": [
  true,
  "rxjs/Rx"
],
````
should be converted to:
```
"no-restricted-imports": ["error", {"paths": ["rxjs/Rx"]}],
```

**Comment by dimabory** [comment]
I'm taking care of it if nobody does mind 🚀
cc @JoshuaKGoldberg
