### ISSUE TITLE
Make trivia/whitespace (Prettier) rules opt-out

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#302]
### 🚀 Feature Request

Following #2 and #301, I really want to harp on the opinion that a linter (ESLint) should be separate from the formatter (Prettier). Having folks need to opt-in with a CLI flag in order to get that behavior will further that cause. 

#### Existing Behavior

Right now, all existing TSLint rules will be output to the ESLint output - even Prettier-related ones such as `whitespace`.

#### Change Proposal

If a rule is disabled by `tslint-config-prettier`, it should only be output if a new CLI flag is provided.

**Comment by KingDarBoja** [comment]
Not an expert on the topic, but maybe [InquirerJS](https://github.com/SBoudrias/Inquirer.js/) would help to accomplish that.

**Comment by JoshuaKGoldberg** [comment]
Hmm, I've thought about this a bit, and I think it'd be better not to surprise users with a change in their configuration. #412's first commit e92888c makes this behavior default with an `--ugly` opt-out. _We_ (linter aficionados) might prefer that but there's a case for users who can't or don't use Prettier getting surprised and irritated by it.

Instead, let's switch to a `--prettier` CLI option as a utility.
