### ISSUE TITLE
Convert prefer-readonly to @typescript-eslint/prefer-readonly

### ISSUE THREAD

**Issue by cheeZery** [typescript-eslint/tslint-to-eslint-config#309]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 0.5.0
-   ESLint version: 6.8.0
-   Node version: 11.10.0

#### Actual Behavior

TSLint rule `prefer-readonly` will be converted to ESLint's `prefer-readonly` (see #181 and #191), but alas that rule doesn't exist in ESLint. As stated [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#maintainability) `prefer-readonly` should be converted to `@typescript-eslint/prefer-readonly`.

#### Expected Behavior

TSLint rule `prefer-readonly` will be converted to @typescript-eslint/eslint-plugin's rule `@typescript-eslint/prefer-readonly`.

**Comment by BO41** [comment]
closed with #310 :wink:

**Comment by JoshuaKGoldberg** [comment]
Aha, thanks! 😄
