### ISSUE TITLE
Conflict on reference types

### ISSUE THREAD

**Issue by beenotung** [typescript-eslint/tslint-to-eslint-config#317]
### 🚀 Feature Request

As mentioned in the issue:
https://github.com/typescript-eslint/typescript-eslint/issues/600

The eslint rule `spaced-comment` does not support reference types syntax, example:
```
/// <reference types="./global" />
```
Will be converted into:
```
// / <reference types="./global" />
```

A configuration in the eslint can fix this:
```
/* eslint spaced-comment: ["error", "always", { "markers": ["/"] }] */
```

However this config is not set by default when converted from `tslint-to-eslint-config`

#### Existing Behavior

Below rule is generated during conversion:
```
        "spaced-comment": "error",
```

#### Change Proposal

Below rule should be generated during conversion:
```
        "spaced-comment": [
            "error",
            "always",
            {
                "markers": ["/"]
            }
        ],
```

**Comment by JoshuaKGoldberg** [comment]
Amusing find! Seems reasonable to always output that `markers` configuration. Accepting PRs!
