### ISSUE TITLE
Doesn't produce a working config

### ISSUE THREAD

**Issue by pronebird** [typescript-eslint/tslint-to-eslint-config#340]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: X.X.X
```
npx tslint-to-eslint-config -- --version

npx: installed 54 in 2.515s
```

-   ESLint version: v6.8.0
-   Node version: v12.9.1

#### Actual Behavior

```
npx tslint-to-eslint-config --config .eslintrc.json
npx eslint .

~/build/src/main/account-data-cache.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: build/src/main/account-data-cache.js.
The file must be included in at least one of the projects provided

[100 times]
```

#### Expected Behavior

Expected for the working config to be produced

#### Reproduction

See above

**Comment by JoshuaKGoldberg** [comment]
Hi @pronebird, thanks for filing an issue on tslint-to-eslint-config!

There's not enough information in your post to go off of. Could you please post your original `tslint.json`, `tsconfig.json`, `package.json`, and any other relevant configuration files?

Closing this issue for now to keep it off the open issues list, but I'll be delighted to reopen it once that info is here.
