### ISSUE TITLE
Consider switching from dependencies.method(...) to inject(method)(...)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#350]
### Overview

It's a little annoying how the [dependency injection](https://martinfowler.com/articles/injection.html) pattern here means you can't F12 / right-click > go-to-definition on injected methods...

#### Actual Behavior

```ts
dependencies.method(/* ... */);
```

#### Expected Behavior

What if an `inject` method were used instead:

```ts
inject(method)(/* ... */)
```

...where `inject.ts` looks something like:

```ts
export const inject = process.env !== 'test'
    ? <Method>(method: Method) => method
    : require('./spies').inject;
```

... and `test-inject.ts` uses a global `Map` of `jest.fn`s that are reset before each test?

```ts
const spies = new Map<[Function, jest.Mock]>();

export const inject = (method: Function) => {
    const existingSpy = spies.get(method);
    if (existingSpy) {
        return spy;
    }
    
    const newSpy = jest.fn();
    spies.add(method, newSpy);
    return newSpy;
};

export const getSpy = <Method>(method: Method): jest.Mock<Method> =>
    spies.get(method) as Method;
```

Tests would then be able to `getSpy(method)` for any injected method...

**Comment by JoshuaKGoldberg** [comment]
I tried it out locally and didn't like it. There's no clean way to prevent accidental calls to the original method. Cool idea though 😄

**Comment by JoshuaKGoldberg** [comment]
Aha, I have it! They'll still take in a first parameter, but it'll be `inject: Inject`. Now they won't have to explicitly declare dependencies.

```ts
export type Inject = <Value>(raw: Value) =>
    Value extends (inject: Inject, ...args: infer Args) => infer Return
    ? (...args: Args) => Return
    : Value;
```

**Comment by KingDarBoja** [comment]
Any progress on this one @JoshuaKGoldberg ? 👅

**Comment by JoshuaKGoldberg** [comment]
Ha, no, I'll just go ahead and close this.

**Comment by KingDarBoja** [comment]
💀 _Rest in Peace_ I though you solved it and got lazy 😆
