### ISSUE TITLE
v0.6.0 not on npm

### ISSUE THREAD

**Issue by neelance** [typescript-eslint/tslint-to-eslint-config#394]
Just asking: Is there a reason why the latest version on npm is still 0.5.1 but 0.6.0 got released on GitHub?

**Comment by JoshuaKGoldberg** [comment]
Grr, looks like the [CI job no longer has the right credentials](https://circleci.com/gh/typescript-eslint/tslint-to-eslint-config/3807). Thanks for spotting @neelance! I'll publish this manually now and file a followup to fix CI.

**Comment by JoshuaKGoldberg** [comment]
✔️ v0.6.0 is on npm. Hooray!

**Comment by neelance** [comment]
Thanks! 👍
