### ISSUE TITLE
Missing converter: one-line

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#410]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 0.6.0
-   `typescript-eslint` version: 2.29.0

#### TSLint Rule Name

`one-line`

See https://github.com/typescript-eslint/tslint-to-eslint-config/issues/401 for a reproduction. 

The [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) indicates `brace-style` is probably the ESLint rule to convert to.

**Comment by KingDarBoja** [comment]
This one will require a notice as the output rule will use the `1tbs` option (_enforces one true brace style_) and any TSLint option will not be taken into account. In other words, it will check any `else`, `catch`, `finally` are on the same line, no matter what.
