### ISSUE TITLE
Missing converter: no-unused-variable

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#411]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 0.6.0
-   `typescript-eslint` version: 2.29.0

#### TSLint Rule Name

`one-line`

See https://github.com/typescript-eslint/tslint-to-eslint-config/issues/401 for a reproduction. 

The [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) indicates `@typescript-eslint/no-unused-vars` is the ESLint rule to convert to. 

Note: that rule has a pretty big caveat in its README.md. There should be a `notice` in the converter for `no-unused-variable` that indicates to read the article.

**Comment by KingDarBoja** [comment]
That's a long article to read indeed but doesn't seem easy to digest for most users. About the caveat, seems fair to do as this is only turn off the ESLint rule.
