### ISSUE TITLE
Add issues for converters for Codelyzer TSLint rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#421]
### 🚀 Feature Request

[Codelyzer](https://github.com/mgechev/codelyzer) provides a set of great TSLint rules around the Angular area. tslint-to-eslint-config should add converters for those rules.

There's a rules list here: https://github.com/mgechev/codelyzer#rules-status. There are quite a lot of them, so for now let's use this issue to track all of them.

FYI @mgechev

Edit: Oh, and see https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/Architecture.md#rule-converters for a description of how the rule converters work. 🔧

**Comment by KingDarBoja** [comment]
This is a nice addition indeed but should be good to link the output ESLint rules as those are at [angular-eslint](https://github.com/angular-eslint/angular-eslint) repo.

**Comment by JoshuaKGoldberg** [comment]
Looks like these are pretty smooth to convert so far. I'll file separate issues for each of the Codelyzr rules and put them in the [Angular Support](https://github.com/typescript-eslint/tslint-to-eslint-config/projects/1) project. I'll consider this issue the tracking one for doing that work.

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg Sounds good to me, I will work on more of them on the weekend, expect several PRs 🚀

**Comment by JoshuaKGoldberg** [comment]
These are all filed and tracked in https://github.com/typescript-eslint/tslint-to-eslint-config/projects/1.

**Comment by JoshuaKGoldberg** [comment]
Just following up: all rules now are either marked as Blocked or have a corresponding PR. Cool

**Comment by highvolt-dev** [comment]
Found a number of rules had been implemented in `angular-eslint` - 8 that my project had missing conversions for.

https://github.com/typescript-eslint/tslint-to-eslint-config/issues/494#issuecomment-787105536

**Comment by highvolt-dev** [comment]
Opened PRs for:

- `template-accessibility-alt-text` (#968)
- `template-accessibility-elements-content` (#969)
- `template-accessibility-label-for` (#973)
- `template-accessibility-table-scope` (#972)
- `template-accessibility-valid-aria` (#971)
- `template-click-events-have-key-events` (#970)
- `template-mouse-events-have-key-events` (#974)
- `template-no-distracting-elements` (#975)

**Comment by JoshuaKGoldberg** [comment]
Incredible, thanks so much for filing those issues & PRs @highvolt-dev! 🤯 👏
