### ISSUE TITLE
 tslint-to-eslint fails to run with import issue

### ISSUE THREAD

**Issue by scottfwalter** [typescript-eslint/tslint-to-eslint-config#431]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.0.0-beta
-   ESLint version: ???
-   Node version: 10.16.0

#### Actual Behavior

npx tslint-to-eslint-config
npx: installed 56 in 4.344s
❌ Could not start tslint-to-eslint: ❌
  Could not import the "@typescript-eslint/eslint-plugin" module. Do you need to install packages?

I've installed "@typescript-eslint/eslint-plugin but no luck

#### Expected Behavior

Not to receive an error

#### Reproduction

**Comment by lwensveen** [comment]
@scottfwalter Try installing globally or vice versa.

**Comment by scottfwalter** [comment]
I found the issue.  I ran it for the first time and it wanted the comments flag.  However during the first execution it generate eslint config file.    If I deleted the eslint config and ran it with the comments flag then it worked.

**Comment by larini** [comment]
> I found the issue. I ran it for the first time and it wanted the comments flag. However during the first execution it generate eslint config file. If I deleted the eslint config and ran it with the comments flag then it worked.

I have the same problem. What did you do, specifically ?

**Comment by pbarranis** [comment]
I ran into the same issue.  All I had to do was npm rm eslint.  It was baffling to get this error since you wouldn't expect eslint already being installed to be a problem.
