### ISSUE TITLE
eslint-plugin-eslint-config-prettie error

### ISSUE THREAD

**Issue by alanhg** [typescript-eslint/tslint-to-eslint-config#439]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.0.0-beta
-   ESLint version: 6.8.0
-   Node version: 10.16.0

#### Actual Behavior

![image](https://user-images.githubusercontent.com/9245110/80798720-9eff9180-8bd7-11ea-8d82-cf183ad9d47d.png)

>   Could not import the "eslint-plugin-eslint-config-prettie" module. Do you need to install packages?

I couldn't find eslint-plugin-eslint-config-prettie package on npm 

#### Expected Behavior

replace comment successfuly

**Comment by JoshuaKGoldberg** [comment]
Fascinating. Thanks for the report @alanhg, this looks like it's probably some kind of add string parsing issue.

`eslint-plugin-eslint-config-prettie` is missing an `r` at the end (and might not need `eslint-plugin-` at the beginning). It should be [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

Until this bug gets fixed, you should be able to get around it by deleting your ESLint configuration file (by default, that's `.eslintrc.js`) before running `tslint-to-eslint-config`.

**Comment by JoshuaKGoldberg** [comment]
Here's the actual error that gets logged:

```
Error: Command failed: eslint --print-config "./.eslintrc.js"

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the plugin "eslint-plugin-eslint-config-prettie".

(The package "eslint-plugin-eslint-config-prettie" was not found when loaded as a Node module from the directory "C:\Code\tslinttest".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-eslint-config-prettie@latest --save-dev

The plugin "eslint-plugin-eslint-config-prettie" was referenced from the config file in ".eslintrc.js".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

It reproduces with an `.eslintrc.js` as simple as:

```js
module.exports = {
  extends: [
    "plugin:eslint-config-prettier",
  ],
};
```

Two issues here:

* The missing `r` feels like an ESLint bug. I'll file a bug on their end.
* https://github.com/prettier/eslint-config-prettier#installation indicates to use an extension like:

    ```js
    {
      "extends": [
        "some-other-config-you-use",
        "prettier"
      ]
    }
    ```

Switching `extends` to use `"prettier"` does fix this issue.

**Comment by Vovch** [comment]
Hi, everyone! 

Stumbled upon this issue in other person's code yesterday.

As a solution I might propose adding the next code:

```
if (slashIndex === -1) {
    const wrongConfigName = JSON.stringify(extendName).slice(1, -1);
    throw new Error(`'extends' requires a configuration name for '${wrongConfigName}', provided after '/' sign.`);
}
```

This way it is possible to also give an understandable error in some cases when the user mistakenly prints `\` sign. E.g.:
`Error: 'extends' requires a configuration name for 'plugin:prettier\recommended', provided after '/' sign.`

instead of:
`ecommende". because there is whitespace in the name. Please check your configuration and remove all whitespace from the plugin name.`

**Comment by haarsh24** [comment]
> ### 🐛 Bug Report
> * `tslint-to-eslint-config` version: 1.0.0-beta
> * ESLint version: 6.8.0
> * Node version: 10.16.0
> 
> #### Actual Behavior
> ![image](https://user-images.githubusercontent.com/9245110/80798720-9eff9180-8bd7-11ea-8d82-cf183ad9d47d.png)
> 
> > Could not import the "eslint-plugin-eslint-config-prettie" module. Do you need to install packages?
> 
> I couldn't find eslint-plugin-eslint-config-prettie package on npm
> 
> #### Expected Behavior
> replace comment successfuly

I'm also getting the same error 
![Capture](https://user-images.githubusercontent.com/48160031/110753975-3f4d2a80-826d-11eb-840c-bb18c5dd36cd.PNG)
