### ISSUE TITLE
Missing Codelyzr (Angular) rule: component-class-suffix

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#465]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

component-class-suffix

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/component-class-suffix

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg this one was already fixed at #432

**Comment by JoshuaKGoldberg** [comment]
Ha, thanks, I missed it 😄
