### ISSUE TITLE
Missing Codelyzr (Angular) rule: component-max-inline-declarations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#466]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

component-max-inline-declarations

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/component-max-inline-declarations

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by KingDarBoja** [comment]
Fixed at #451 😛 @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
oy vey
