### ISSUE TITLE
Missing Codelyzr (Angular) rule: component-selector

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#467]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

component-selector

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/component-selector

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by KingDarBoja** [comment]
Psss, this one was fixed at #452 @JoshuaKGoldberg
