### ISSUE TITLE
Missing Codelyzer (Angular) rule: import-destructuring-spacing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#472]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

import-destructuring-spacing

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/import-destructuring-spacing

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by JoshuaKGoldberg** [comment]
Closing as [angular-eslint](https://github.com/angular-eslint/angular-eslint/) does not yet have an equivalent for this rule. 💀 

If you're seeing this and they've since added one, hooray! Post here and we can re-open it. Feel free to send a pull request resolving this issue.

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/angular-eslint/angular-eslint/pull/219 this is as done as it will ever be.

**Comment by KingDarBoja** [comment]
_RIP import-destructuring-spacing_

But shouldn't we display a notice explaining this rule is gone, reduced to atoms?

**Comment by JoshuaKGoldberg** [comment]
Blocked on #1063.
