### ISSUE TITLE
Missing Codelyzer (Angular) rule: prefer-inline-decorator

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#490]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

prefer-inline-decorator

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/prefer-inline-decorator

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by JoshuaKGoldberg** [comment]
Closing as [angular-eslint](https://github.com/angular-eslint/angular-eslint/) does not yet have an equivalent for this rule. 💀 

If you're seeing this and they've since added one, hooray! Post here and we can re-open it. Feel free to send a pull request resolving this issue.

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/angular-eslint/angular-eslint/pull/333 this is as done as it will ever be.

**Comment by KingDarBoja** [comment]
Same thing as #472, maybe a notice for those rules that won't be fixed like the one at angular-eslint:

> This TSLint rule should be replaced by a dedicated code formatter, such as Prettier
