### ISSUE TITLE
Missing Codelyzr (Angular) rule: template-cyclomatic-complexity

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#503]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

template-cyclomatic-complexity

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/template-cyclomatic-complexity

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by JoshuaKGoldberg** [comment]
Closing as [angular-eslint](https://github.com/angular-eslint/angular-eslint/) does not yet have an equivalent for this rule. 💀 

If you're seeing this and they've since added one, hooray! Post here and we can re-open it. Feel free to send a pull request resolving this issue.

**Comment by bbarry** [comment]
`@angular-eslint/template/cyclomatic-complexity`
