### ISSUE TITLE
Missing Codelyzer (Angular) rule: template-no-negated-async

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#510]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

template-no-negated-async

#### Package Source

**Codelyzr**: http://codelyzer.com/rules/template-no-negated-async

Splitting out from #421, this issue tracks adding in a missing Codelyzr rule converter.

**Comment by JoshuaKGoldberg** [comment]
Closing as [angular-eslint](https://github.com/angular-eslint/angular-eslint/) does not yet have an equivalent for this rule. 💀 

If you're seeing this and they've since added one, hooray! Post here and we can re-open it. Feel free to send a pull request resolving this issue.

**Comment by bbarry** [comment]
Isn't `@angular-eslint/template/no-negated-async` the rule for this?

looking at https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/all.json and the tests for this rule https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin-template/tests/rules/no-negated-async.test.ts

**Comment by JoshuaKGoldberg** [comment]
Aha, thanks so much for pointing this out @bbarry! I'll go ahead and mark these issues as accepting PRs.

The closed PRs I sent that are each linked to an issue can serve as reference (though they'll need to be updated for the correct rule names).
