### ISSUE TITLE
Missing tslint-react rule: jsx-alignment

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#515]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

jsx-alignment

#### Package Source

**tslint-react**: https://github.com/palantir/tslint-react (see [#rules](https://github.com/palantir/tslint-react#rules))

Equivalents for tslint-react rules generally live in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by KingDarBoja** [comment]
@JoshuaKGoldberg I haven't found this rule equivalent on the eslint-plugin-react repo. I asked for some roadmap table which address the equivalents on this [tslint-react issue](https://github.com/palantir/tslint-react/issues/210).

**Comment by KingDarBoja** [comment]
**UPDATE** This rule is being discussed at https://github.com/yannickcr/eslint-plugin-react/issues/2735 which could make use of https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md by setting `maximum` option to 1 for multiline declaration (which requires a PR at the linked issue).

Closing this for now while waiting for it.
