### ISSUE TITLE
Missing tslint-react rule: jsx-no-lambda

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#523]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

jsx-no-lambda

#### Package Source

**tslint-react**: https://github.com/palantir/tslint-react (see [#rules](https://github.com/palantir/tslint-react#rules))

Equivalents for tslint-react rules generally live in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by rpanday** [comment]
I tried fixing this. The conversation at https://github.com/yannickcr/eslint-plugin-react/issues/2176 suggests that an equivalent rule is not present. If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by KingDarBoja** [comment]
Based on the linked conversation, this rule shouldn't have a converter but we need to tackle it with some notice and providing a empty rule result (no operation maybe?) to let users know about a similar rule at `eslint-plugin-react`.

cc @JoshuaKGoldberg
