### ISSUE TITLE
Missing tslint-react rule: jsx-no-multiline-js

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#524]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

jsx-no-multiline-js

#### Package Source

**tslint-react**: https://github.com/palantir/tslint-react (see [#rules](https://github.com/palantir/tslint-react#rules))

Equivalents for tslint-react rules generally live in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by sonalisaxenacse12** [comment]
@JoshuaKGoldberg, there is no equivalent rule for jsx-no-multiline-js in [eslint-plugin-react ](https://github.com/yannickcr/eslint-plugin-react), also there is an ongoing [conversation](https://github.com/yannickcr/eslint-plugin-react/issues/2516) that discuss this.

We can close this issue for now.

**Comment by KingDarBoja** [comment]
Will close this as the current rule is not implemented (yet) on **eslint-plugin-react**.
