### ISSUE TITLE
Missing tslint-react rule: jsx-self-close

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#525]
### Missing Converter

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

jsx-self-close

#### Package Source

**tslint-react**: https://github.com/palantir/tslint-react (see [#rules](https://github.com/palantir/tslint-react#rules))

Equivalents for tslint-react rules generally live in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by prnvdixit** [comment]
@JoshuaKGoldberg I can see that no one is working on this, I'll pick this up :smile:

**Comment by KingDarBoja** [comment]
The equivalent rule is actually not JSX specific: [self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md).

The best approach should be showing a warning about using this rule since `jsx-self-close` got removed and there is no equivalent.

**Comment by prnvdixit** [comment]
Yeah, I realized it after I had made a PR (didn't verified it earlier, hence closed the PR).

@KingDarBoja Is showing a warning something that should get picked up as a part of this PR? Or should we be deferring to work on this issue until a corresponding JSX-specific rule is added to eslint-plugin-react?

**Comment by KingDarBoja** [comment]
Sorry for the late response but after looking into my previous comment, the rule `self-closing-comp` is indeed the correct one, it is just the name that changed as most **tslint-react** rules applies to React **and** JSX.
