### ISSUE TITLE
Missing tslint-react rule: jsx-space-before-trailing-slash

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#526]
### Missing jsx-space-before-trailing-slash

-   `tslint-to-eslint-config` version: 1.0.0-beta

-   `typescript-eslint` version: 2.31.0

#### TSLint Rule Name

jsx-space-before-trailing-slash

#### Package Source

**tslint-react**: https://github.com/palantir/tslint-react (see [#rules](https://github.com/palantir/tslint-react#rules))

Equivalents for tslint-react rules generally live in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react). If an ESLint rule equivalent doesn't yet exist, this tslint-to-eslint-config issue can be closed until that equivalent is created.

**Comment by bhavinkotak07** [comment]
Hi Team! I would like to work on this issue.

**Comment by bhavinkotak07** [comment]
@JoshuaKGoldberg Looks like ESLint rule equivalent doesn't yet for this particular rule. The issue can be closed.

**Comment by KingDarBoja** [comment]
The rule equivalent is https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-space-before-closing.md

**Comment by vignanl** [comment]
Hi,
I would like to work on this issue, I checked the URl, it is mentioned jsx-space-before-closing rule is deprecated and suggested to use jsx-tag-spacing with rule options beforeSelfClosing which can be set to "always or never".

Tslint rule jsx-space-before-trailing-slash has no arguments and it means always, so for eslint rule jsx-tag-spacing
below object is constant. can i go ahead with this assumption ? 
{
  "closingSlash": "never",
  "beforeSelfClosing": "always",
  "afterOpening": "never",
  "beforeClosing": "allow"
}

**Comment by KingDarBoja** [comment]
From TSLint:

> Checks that self-closing JSX elements have a space before the '/>' part.

From ESLint:

> https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md#beforeselfclosing

Seems to be only for `beforeSelfClosing` only ("always" in this case), as the originalTSLint only checks for `/>` tag.
