### ISSUE TITLE
Recognize tslint-react as an extended ruleset

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#528]
### 🚀 Feature Request

If a TSLint configuration extends from [`tslint-react`](https://github.com/palantir/tslint-react), we should know to make the output ESLint configuration extend from [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react).

#### Existing Behavior

The React community plugins are not recognized by `collectTSLintRuleset`''s native extensions list.

#### Change Proposal

Add `tslint-react` -> `eslint-plugin-react` to that list.

**Comment by yasarsid** [comment]
I see no one has picked this - Will start working on this.

**Comment by yasarsid** [comment]
@JoshuaKGoldberg  Would appreciate if you could have a look at this PR 👍
