### ISSUE TITLE
class-name convert deprecated. Rename to naming-convention

### ISSUE THREAD

**Issue by GrzesiekP** [typescript-eslint/tslint-to-eslint-config#596]
It's ot actually missing, but rule name is out of date.
[typescript-eslint issue with explaination](https://github.com/typescript-eslint/typescript-eslint/issues/1854#issuecomment-609913921)
I've a PR, so you can let me know when you accept it and I'll submit.

### 💥 Missing Converter

-   `tslint-to-eslint-config` version: latest
-   `typescript-eslint` version: 3.0.2

#### TSLint Rule Name

**class-name**

**Comment by JoshuaKGoldberg** [comment]
Thanks for the heads up @GrzesiekP. A PR would be great!

**Comment by KingDarBoja** [comment]
Re-opening as this rule converter hasn't been fixed. This will require a merger as several rules are now converter into `naming-convention` one.
