### ISSUE TITLE
Could not import the "eslint module. Do you need to install packages?

### ISSUE THREAD

**Issue by ChrissW-R1** [typescript-eslint/tslint-to-eslint-config#626]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.0.0
-   ESLint version: 7.3.1
-   Node version: 14.5.0

#### Actual Behavior

The following error occurs:
> ❌ Could not start tslint-to-eslint: ❌
>   Could not import the "eslint module. Do you need to install packages?

#### Expected Behavior

The converter works and will run!

#### Reproduction

1. Install Node and TSLint
2. Start the converter with "npx tslint-to-eslint-config"

**Comment by ChrissW-R1** [comment]
Very interesting is the name:
> "eslint

Which looks, like a part of the module name is missing. (No closing quote mark)

**Comment by ChrissW-R1** [comment]
Error found in corrupted tslint.json

**Comment by KingDarBoja** [comment]
Glad to hear you solved the issue, at the end was a corrupted tslint.json or something else?

**Comment by ChrissW-R1** [comment]
It was only one keyword in the tslint.json. My IDE changed
`"extends":        "tslint:recommended",`
to
`"extends":        "eslint:recommended",`

That's all.
