### ISSUE TITLE
CLI Flags do not work for nodejs 14

### ISSUE THREAD

**Issue by kevinprotoss** [typescript-eslint/tslint-to-eslint-config#660]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 1.1.0
-   ESLint version: 7.5.0
-   Node version: 14.6.0

#### Actual Behavior

I just used the recommended command `npx tslint-to-eslint-config --prettier` to convert the lint config. However, I always get the suggestion in the logging message: 
```
☠ Prettier plugins are missing from your configuration. ☠
  We highly recommend running tslint-to-eslint-config --prettier to disable formatting ESLint rules.
  See https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md#should-i-use-prettier.
```
Meanwhile, no configurations about prettier would be inserted in the generted .eslintrc.js file.

I wonder what's wrong here. Did I forget some required plugins or  install wrong version of those dependencies? 
I know some more dependencies are requied here for further use together with eslint. I just want to first make sure the convertion of lint configuration is correct. Unfortunately, it doesn't work for me. 

#### Expected Behavior

No more suggestions in the console message. 
Relevant config values for prettier would be added into the .eslintrc.js

#### Reproduction

Use nodejs 14.6.0

```
npm install -g @angular/cli
ng new my-dream-app
cd my-dream-app
npm i --save-dev eslint
npx tslint-to-eslint-config --prettier
```

**Comment by JoshuaKGoldberg** [comment]
Fascinating. It looks like the options getting parsed aren't including `prettier` in https://github.com/typescript-eslint/tslint-to-eslint-config/blob/b72288708fb5c4e00ce2f1921b039097e91ae2b2/src/cli/runCli.ts#L38 .

Switching to using `.opts()` fixes it. I'll send a PR.
