### ISSUE TITLE
Switch default branch to 'main'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#673]
🖤

**Comment by KingDarBoja** [comment]
Not a fan of the reasoning behind this change but I am not against it 🚀

**Comment by JoshuaKGoldberg** [comment]
Ah, incredible timing (seriously, I did not know about this blog post until after filing this issue!: https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/

I'll go ahead and make the change now.
