### ISSUE TITLE
missing merger: @typescript-eslint/naming-convention

### ISSUE THREAD

**Issue by manavortex** [typescript-eslint/tslint-to-eslint-config#676]
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 6.14.5
-   ESLint version: 7.6.0

#### CLI Output

<pre>
npx tslint-to-eslint-config --prettier

✨ 89 rules replaced with their ESLint equivalents. ✨

❗ 3 ESLint rules behave differently from their TSLint counterparts ❗
  Check ./tslint-to-eslint-config.log for details.

❌ 1 error thrown. ❌

❓ 8 rules are not known by tslint-to-eslint-config to have ESLint equivalents. ❓
  The "@typescript-eslint/tslint/config" section of ./.eslintrc.js configures eslint-plugin-tslint to run them in TSLint within ESLint.
  Check ./tslint-to-eslint-config.log for details.

♻ Consider using --comments to replace TSLint comment directives in your source files. ♻

⚡ 10 new packages are required for this ESLint configuration. ⚡
  npm install @angular-eslint/eslint-plugin @angular-eslint/eslint-plugin-template @typescript-eslint/eslint-plugin @typescript-eslint/eslint-plugin-tslint @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-import eslint-plugin-jsdoc eslint-plugin-react --save-dev

✅ All is well! ✅
</pre>

#### File Output

<pre>
3 ESLint rules behave differently from their TSLint counterparts:
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.
  * @typescript-eslint/no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.

Error: multiple output @typescript-eslint/naming-convention ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md. Thanks!

8 rules are not known by tslint-to-eslint-config to have ESLint equivalents:
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "function-name".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "import-name".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-else-after-return".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-function-constructor-with-string-args".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-increment-decrement".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "object-shorthand-properties-first".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-array-literal".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "ter-prefer-arrow-callback".
</pre>

#### Reproduction

tsconfig.json
<pre>
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "resolveJsonModule": true,
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
  }
}

</pre>
tslint.json

<pre>
{
  "extends": ["tslint-config-airbnb", "tslint-angular", "tslint-config-prettier"],
  "rules": {
    "directive-selector": [true, "attribute", "myapp", "camelCase"],
    "component-selector": [true, "element", "myapp", "kebab-case"],
    "jsdoc-format": [true, "check-multiline-start"]
  }
}
</pre>

package.json
<pre>
    "eslint": "^7.6.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-import-helpers": "^1.1.0",
    "eslint-config-prettier": "^6.11.0",
    "@typescript-eslint/eslint-plugin": "^3.8.0",
    "@typescript-eslint/eslint-plugin-tslint": "^3.8.0",
    "@typescript-eslint/parser": "^3.8.0",
    "tslint": "~5.18.0",
</pre>

**Comment by KingDarBoja** [comment]
Already reported at #666
