### ISSUE TITLE
FAQ corrupt

### ISSUE THREAD

**Issue by buzzub** [typescript-eslint/tslint-to-eslint-config#696]
The FAQs at https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md have gibberish at the end and need updating.

**Comment by buzzub** [comment]
...unless it's an intentional joke? 🤷‍♀️

**Comment by JoshuaKGoldberg** [comment]
@buzzub yes, it's an intentional joke 😄 . https://github.com/typescript-eslint/tslint-to-eslint-config/pull/348#discussion_r400026097

Thanks for the report though!
