### ISSUE TITLE
converting tslint.indent to eslint.@typescript-eslint/indent should also convert occurances of tabs to tab

### ISSUE THREAD

**Issue by jonnytest1** [typescript-eslint/tslint-to-eslint-config#711]
### 🐛 Bug Report

indent tabs =>  @typescript-eslint/indent tab

**Comment by JoshuaKGoldberg** [comment]
Hi @jonnytest1, thanks for filing an issue on tslint-to-eslint-config! There's not much information on your post to go on, so it's hard to understand what should be done. Could you please fill out **all** of the [bug report template](https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=bug_report.md)?

**Comment by kuzivany** [comment]
If I'm not mistaken, @jonnytest1 may be referring to the incorrect conversion for `"tabs"` in the `indent` rule.
When using [tabs in TSLint](https://palantir.github.io/tslint/rules/indent/) the [ESLint `indent` rule](https://eslint.org/docs/rules/indent#options) option is `"tab"`, not `"tabs"`.

The `.eslintrc.js` generated by running `npx tslint-to-eslint-config` has the following `indent` rule:

```javascript
        // .eslintrc.js
        // ...
        "@typescript-eslint/indent": [
            "error",
            "tabs"
            // ...
```

Which according to [ESLint](https://eslint.org/docs/rules/indent#options) should be:

```javascript
        // .eslintrc.js
        // ...
        "@typescript-eslint/indent": [
            "error",
            "tab"
            // ...
```

```diff
-           "tabs"
+           "tab"
```

**Comment by JoshuaKGoldberg** [comment]
Ah, that's a great catch. Thanks, yes!
