### ISSUE TITLE
Provide node API for config conversion logic

### ISSUE THREAD

**Issue by JamesHenry** [typescript-eslint/tslint-to-eslint-config#729]
#### Existing Behavior

The library can be leveraged via a CLI and interacts directly with disk.

#### Change Proposal

Provide the option of leveraging (part of) the library in code via a node API which would only focus on the config conversion process.

After discussing this with @JoshuaKGoldberg it seems we essentially want to expose (potentially after some tweaks) the `convertLintConfig` function: https://github.com/typescript-eslint/tslint-to-eslint-config/blob/e425bab57c2b7ac84621abdfd86b3e6954ca9948/src/converters/lintConfigs/convertLintConfig.ts#L22

**Comment by JoshuaKGoldberg** [comment]
Just posting notes from our chat: this is definitely doable and something we'd want to expose. There are actually quite a few pieces that go into converting to an output ESLint config:
* Original TSLint rules, both as the raw `tslint.json` contents and the result of `tslint --print-config`
* Original ESLint rules, if a config already exists (`originalConfigurations.eslint`)
* TypeScript settings (`tsconfig.json`)
* Node package contents (`package.json`)

Out of those, only the (reported?) `tslint.json` ones are really necessary. I don’t quite remember off the top of my head why both are there, but IIRC there was a reason. More investigation required 😄
