### ISSUE TITLE
Consider enabling createDefaultProgram

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#739]
### 🚀 Feature Request

Forking conversation from https://github.com/typescript-eslint/tslint-to-eslint-config/issues/738#issuecomment-706321235:

> Also, I have seen this fix on many other issues and wonder why it doesn't get placed on default if it fixes many issues.
> 
> In .eslintrc.js inside "parserOptions" placing
> 
> ```js
> 'createDefaultProgram': true
> ```
>
> Seems to fix a lot of eslint issues with my IDE. 

#### Existing Behavior

`createDefaultProgram` is not mentioned anywhere in this repository.

#### Change Proposal

Should it be included in the default output configuration? If so, should it be always on, opt-in with a flag, or opt-out with a flag?

Investigation required!

**Comment by adidahiya** [comment]
I don't think this option should be enabled by default. From the [README](https://github.com/typescript-eslint/typescript-eslint/blob/f887ab51f58c1b3571f9a14832864bc0ca59623f/packages/parser/README.md#parseroptionscreatedefaultprogram):

> Using this option will incur significant performance costs. This option is primarily included for backwards-compatibility.

This performance hit was true in practice in the Blueprint repo, where we initially enabled it and then [disabled](https://github.com/palantir/blueprint/pull/4078) the option. So I don't think tslint-to-eslint-config should encourage its usage.

**Comment by JoshuaKGoldberg** [comment]
That's a very good reason not to. Thanks!

**Comment by idemax** [comment]
any update?
