### ISSUE TITLE
Use a diff writer instead of complete override for JSON editor config conversions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#744]
### 🚀 Feature Request

Forking from #742: editor configs can have a lot of formatting considerations in them that we won't want to override. Spacing, sorting, comments, trailing commas or lack thereof: these are all things that should be preserved when writing a new config.

#### Existing Behavior

We directly write the results of `JSON.stringify()`ing a new computed editor config. 

#### Change Proposal

Use something like [`jsondiffpatch`](https://github.com/benjamine/jsondiffpatch) to write the new config.

Note: this issue will also apply to Atom's CSON configs (#728).

**Comment by KingDarBoja** [comment]
Oh yes, this is a edge case but seems that json with comments is getting popular on recent user development tools, I am up for it.

**Comment by JoshuaKGoldberg** [comment]
Hmm, `jsondiffpatch` looks like it deals only with the parsed objects, not the raw source file text... so it's likely another library would need to be used.

**Comment by JoshuaKGoldberg** [comment]
https://en.wikipedia.org/wiki/JSON_Patch looks like what we're looking for.

**Comment by JoshuaKGoldberg** [comment]
Hmm, that one works on document objects. Maybe it'd be easier to go with native TypeScript APIs, since that's already used for the file comment parsing... https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
