### ISSUE TITLE
Switch editor config conversions to opt-in

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#745]
### 🚀 Feature Request

Forking from #742: should editor config conversions not be applied if `--editor` isn't specified?

#### Existing Behavior

If a `.vscode/settings.json` exists, `tslint-to-eslint-config` will run on it.

#### Change Proposal

This can be surprising to users: they may not want to convert their editor config, and prior to #742 and #744 being resolved, this can be a destructive operation. Should we make conversion...

* ...opt-in until those two issues are resolved?
* ...opt-in even after those two issues are resolved?

Personally, I'm in favor of keeping the existing behavior because both those issues are pretty straightforward to resolve: there are already packages for [JSON5](https://json5.org) and [JSON diff patching](https://github.com/benjamine/jsondiffpatch). But we should discuss a bit instead of letting me steamroll 😄. What do you think, @KingDarBoja and @SgtPooki?

**Comment by KingDarBoja** [comment]
I do rather make it opt-in as users would not want to update editor config or maybe, just maybe, the editor setup isn't supported at all (Emacs, vim, etc).

**Comment by JoshuaKGoldberg** [comment]
Sounds like that's two votes in favor of opt-in then 😄
