### ISSUE TITLE
rxjs-tslint-rules

### ISSUE THREAD

**Issue by criskrzysiu** [typescript-eslint/tslint-to-eslint-config#762]
#### TSLint Rule Name
most rules from here 
https://github.com/cartant/rxjs-tslint-rules

#### Package Source
https://github.com/cartant/eslint-plugin-rxjs
https://github.com/cartant/eslint-plugin-rxjs-angular

**Comment by JoshuaKGoldberg** [comment]
Indeed, yes please!

I'll mark this as accepting PRs now, though it'd be nice to have a separate issue for each rule. I'll try to get around to filing those & setting up a project soon. Thanks for posting @criskrzysiu!

**Comment by criskrzysiu** [comment]
I will try to create PR, although I've never done anything like this so it may take some time :) I think it would be nice to mark some PR as an example of how to implement a new rule.

**Comment by criskrzysiu** [comment]
I think it would be wise to add a project for all of the rxjs-tslint-rules rules as there is many of them and it would be nice to track the progress on it

**Comment by criskrzysiu** [comment]
bdw, starting with all recommended ones

**Comment by KingDarBoja** [comment]
I have created a project to keep track of all rxjs related converters, thanks to @criskrzysiu for creating the issues. Closing this :)
