### ISSUE TITLE
rxjs-no-async-subscribe

### ISSUE THREAD

**Issue by criskrzysiu** [typescript-eslint/tslint-to-eslint-config#774]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 1.5.0
-   `typescript-eslint` version: 4.6.0

#### TSLint Rule Name
[rxjs-no-async-subscribe](https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoAsyncSubscribeRule.ts)

#### Package Source
[rxjs-tslint-rules](https://github.com/cartant/rxjs-tslint-rules#rules)

#### ESLint Rule Name
[eslint-plugin-rxjs/no-async-subscribe](https://github.com/cartant/eslint-plugin-rxjs/blob/main/source/rules/no-async-subscribe.ts)

**Comment by criskrzysiu** [comment]
First of many as asked by @JoshuaKGoldberg to create a new issue per rule... that's gonna take some time ;) 

https://github.com/typescript-eslint/tslint-to-eslint-config/issues/762

**Comment by criskrzysiu** [comment]
if we merge that I will add converters to all other rxjs-* rules

**Comment by KingDarBoja** [comment]
@criskrzysiu Done! Thanks for contributing :)
