### ISSUE TITLE
simpleRuleConverter and argument helpers for simple cases 

### ISSUE THREAD

**Issue by criskrzysiu** [typescript-eslint/tslint-to-eslint-config#813]
### 🚀 Feature Request

1. I think it is tedious to create all the files, tests, etc... for simple rule converters that are basically changing the name, adding plugins and that's it. For such plugins, it would be great to add a simple helper function or even an additional place that we just pass those simple values.

2.  For simple cases of argument mapping we could add a mapping function that would help with that. 

#### Existing Behavior

Even a simple rule takes at least 2 new files and 1 change in the existing one - often copy-pasting code. 

#### Change Proposal

PR in progress

**Comment by JoshuaKGoldberg** [comment]
👋  @criskrzysiu are you still interested in tackling this? No worries if not, I can if you don't have time!

**Comment by JoshuaKGoldberg** [comment]
I'm going to close this issue for aging out. Now that we have a utility script to auto-generate those templating files (#1089) I'm not convinced this is worth the effort.

Please post back here if you disagree!
