### ISSUE TITLE
Unclear error message when tslint command is not found

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#836]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.0.0
-   ESLint version: N/A
-   Node version: N/A

#### Actual Behavior

```
❌ Could not start tslint-to-eslint: ❌
  Command failed: tslint --print-config "./tslint.json"
/bin/sh: tslint: command not found
```

#### Expected Behavior

```
❌ Could not start tslint-to-eslint: ❌
    The 'tslint' command was not found. Either install it globally or add it as a devDependency of this repository.
```

#### Reproduction

Per @kumaresan-subramani's info in #823:

```
git clone https://github.com/kumaresan-subramani/ESlint-tester
cd ESlint-tester
npx tslint-to-eslint-config
```

I'm guessing this hasn't been reported until now because most projects that use TSLint and would want to convert to ESLint already have it as a dependency in their `package.json`.

I already have a fix for it from just testing this out locally, so I'll send a PR 😄 .

**Comment by kumaresan-subramani** [comment]
@JoshuaKGoldberg , did you find anything regarding this

**Comment by JoshuaKGoldberg** [comment]
@kumaresan-subramani yup, it should have been resolved in #837. Are you still experiencing it with the latest 2.0.1 version?

**Comment by kumaresan-subramani** [comment]
yes brother, same issue latest too

**Comment by JoshuaKGoldberg** [comment]
Okie, I'll take a look.

To be clear, this issue is reporting that the error message is unclear. The resolution you the consumer will need to do is in the new proposed error message: either install the `tslint` package globally or add it as a devDependency of your package.

**Comment by kumaresan-subramani** [comment]
@JoshuaKGoldberg ,

i think below is an issue cause

![image](https://user-images.githubusercontent.com/36756050/102175946-5e365d80-3ec6-11eb-89ab-4a6ef4c50790.png)

while using `npx tslint-to-eslint-config` command it tries to access `tslint` file from `node_modules` instead of root.

### But works fine when i initialize ES0lint using below doc

https://eslint.org/docs/user-guide/getting-started#installation-and-usage

**Comment by kumaresan-subramani** [comment]
## Alternate

i have tried below as alternate

https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint#installation

## below is my `eslint.json file`

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint",
        "@typescript-eslint/tslint"
    ],
    "parserOptions": {
        "project": "tsconfig.json"
    },
    "rules": {
        "@typescript-eslint/tslint/config": ["warn", {
          "lintFile": "https://github.com/kumaresan-subramani/ESlint-tester/blob/main/tslint.json", // path to tslint.json of your project
          "rules": {
            },
          "rulesDirectory": [
            // array of paths to directories with rules, e.g. 'node_modules/tslint/lib/rules' (will be used if `lintFile` is not specified)
          ]
        }]
      },
    "reportUnusedDisableDirectives": true

}
```

while giving below command, i am facing memry issue

`yarn run eslint src`

### issue

`javascript heap out of memory`

**Comment by kumaresan-subramani** [comment]
i found my issue

https://github.com/typescript-eslint/tslint-to-eslint-config#usage

i have tslint version at 4.0.2

when i upgrade latest it wokrs fine
