### ISSUE TITLE
ng add @angular-eslint/schematics@latest fails trying to install coffeescript@1.12.8

### ISSUE THREAD

**Issue by skovalyov** [typescript-eslint/tslint-to-eslint-config#839]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.0.0-beta5 (from the latest release https://github.com/angular-eslint/angular-eslint/blob/69303fa600e471abe5e719216179b1bdbb9662da/packages/schematics/package.json)
-   ESLint version: ^7.6.0 (from the latest release https://github.com/angular-eslint/angular-eslint/blob/69303fa600e471abe5e719216179b1bdbb9662da/packages/schematics/package.json)
-   Node version: 14.15.1

#### Actual Behavior

`ng add @angular-eslint/schematics@latest` fails during installing packages for tooling via npm phase.
#### Expected Behavior

`ng add @angular-eslint/schematics@latest` should install all the relevant packages for migrating an Angular CLI project from Codelyzer and TSLint.

#### Reproduction

1. Go to an Angular CLI project folder in a terminal.
2. Run `ng add @angular-eslint/schematics@latest`.
3. Wait before it fails with an error:

```
$ ng add @angular-eslint/schematics@latest
Installing packages for tooling via npm.
An unhandled exception occurred: npm ERR! code E404
npm ERR! 404 Not Found - GET http://my-local-sinopia-npm-registry/coffeescript/-/coffeescript-1.12.8.tgz
npm ERR! 404
npm ERR! 404  'coffeescript@^1.10.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cson-parser'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Apparently the error occurs because of `cson-parser`, which has `coffeescript` as a dependency, which I mentioned at https://github.com/typescript-eslint/tslint-to-eslint-config/pull/728#discussion_r525133594

Even the latest `cson-parser` uses `"coffeescript": "^1.12.7"`, which results in attempt to install non-existent `coffeescript@1.12.8`. The problem has been earlier discussed in other repositories such as https://github.com/npm/registry-issue-archive/issues/248

#### Environment

- Windows 10 Enterprise.
- Cygwin.
- Corporate Sinopia npm registry.

**Comment by KingDarBoja** [comment]
The proper way of fixing it is to ask cson-parser maintainers to pin the coffescript version to `1.12.7` as their [package.json](https://github.com/groupon/cson-parser/blob/master/package.json#L44) uses a minor range semantic version

**Comment by KingDarBoja** [comment]
Alright, `cson-parser` got updated at #841, @JoshuaKGoldberg can you provide a patch release to see if this solves the issue? 👨‍🎤

**Comment by JoshuaKGoldberg** [comment]
Okie dokie, thanks for pushing on this! https://www.npmjs.com/package/tslint-to-eslint-config/v/2.0.1 is released and should fix this issue. Please do post here if it's still broken!

**Comment by skovalyov** [comment]
Thank you for the fix! Now I simply wait for https://github.com/angular-eslint new release, which should point to the latest release of https://github.com/typescript-eslint/tslint-to-eslint-config in https://github.com/angular-eslint/angular-eslint/blob/master/packages/schematics/package.json so that I can use `ng add @angular-eslint/schematics`

**Comment by amit2206** [comment]
Hi All, one issue I am face same as this I am trying to update by tslint to ESLint using commant - ng add @angular-eslint/schematics
But I am getting following error - 
npm WARN old lockfile 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sdwan-ui-refactor@0.0.0
npm ERR! Found: @angular/cli@13.3.5
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"^13.2.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@">= 12.0.0 < 13.0.0" from @angular-eslint/schematics@12.7.0
npm ERR! node_modules/@angular-eslint/schematics
npm ERR!   dev @angular-eslint/schematics@"12.7.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/guest/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guest/.npm/_logs/2022-05-18T16_16_35_620Z-debug.log


Any suggestions ?
