### ISSUE TITLE
Missing nx plugin converter: enforce-module-boundaries

### ISSUE THREAD

**Issue by KingDarBoja** [typescript-eslint/tslint-to-eslint-config#917]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 2.0.1
-   `typescript-eslint` version: 4.9.1

#### TSLint Rule Name

`enforce-module-boundaries`

This rule lives inside the nx workspace repository. This is (AFAIK) going to be handled at https://github.com/nrwl/nx/pull/4328.

#### Package Source

The ESLint plugin can be found at [eslint-plugin-nx](https://github.com/nrwl/nx/tree/master/packages/eslint-plugin-nx), inside packages directory from nx workspace repository.

The converter doesn't need to be added as it is handled by the plugin itself and is pretty specific of nx workspace but wanted to let a note for anyone looking for it and also keep an eye of the state of automated migrations from TSLint to ESLint. 🎸

**Comment by JoshuaKGoldberg** [comment]
@KingDarBoja good to know 👍. Just to be clear, if there's no converter to be added, is there any code change to be done on our side?

**Comment by KingDarBoja** [comment]
No changes on our side at the moment as this converter is exclusively being handled by NX Workspaces repository. Any migration between TSLint and ESLint is gonna be handled by that PR schematic AFAIK.

**Comment by JamesHenry** [comment]
Yes, thanks folks, this rule is only ever relevant within an Nx workspace, and in that context Nx handles everything for you.

I have completed a custom implementation of the conversion within Nx itself, so this can be closed.

Thanks!
