### ISSUE TITLE
multiple output react/jsx-no-bind ESLint rule options 

### ISSUE THREAD

**Issue by HeikoKochBuR** [typescript-eslint/tslint-to-eslint-config#930]
### 💥 Missing Merger

-   `tslint-to-eslint-config` version:6.14.10
-   ESLint version: 7.18.0

#### CLI Output

npx: installed 60 in 7.215s
 
✨ 106 rules replaced with their ESLint equivalents. ✨
 
❗ 9 ESLint rules behave differently from their TSLint counterparts ❗
  Check ./tslint-to-eslint-config.log for details.
 
❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.
 
❓ 10 rules are not known by tslint-to-eslint-config to have ESLint equivalents. ❓
  The "@typescript-eslint/tslint/config" section of ./.eslintrc.js configures eslint-plugin-tslint to run them in TSLint within ESLint.
  Check ./tslint-to-eslint-config.log for details.
 
☠ Prettier plugins are missing from your configuration. ☠
  We highly recommend running tslint-to-eslint-config --prettier to disable formatting ESLint rules.
  See https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md#should-i-use-prettier.
 
⚡ 7 new packages are required for this ESLint configuration. ⚡
  npm install @typescript-eslint/eslint-plugin-tslint eslint-plugin-import eslint-plugin-jsdoc eslint-plugin-no-null eslint-plugin-prefer-arrow eslint-plugin-react eslint-plugin-unicorn --save-dev
 
♻ Consider using --comments to replace TSLint comment directives in your source files. ♻
 
✅ All is well! ✅

#### File Output

9 ESLint rules behave differently from their TSLint counterparts:
  * arrow-body-style:
    - ESLint will throw an error if the function body is multiline yet has a one-line return on it.
  * react/jsx-no-bind:
    - ESLint rule 'jsx-no-bind' also checks for arrow functions
  * import/no-extraneous-dependencies:
    - ESLint does not support whitelisting modules
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * @typescript-eslint/no-unused-vars:
    - Please read the following article as the rule behaviour may change on the short term: https://github.com/typescript-eslint/typescript-eslint/issues/1856
  * @typescript-eslint/no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * @typescript-eslint/quotes:
    - Option "jsx-double" is not supported by ESLint.
  * space-before-function-paren:
    - Option "constructor" is not supported by ESLint.
    - Option "method" is not supported by ESLint.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.

**Error: multiple output react/jsx-no-bind ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md. Thanks!**

10 rules are not known by tslint-to-eslint-config to have ESLint equivalents:
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "import-spacing".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "jsx-alignment".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "jsx-no-string-ref".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "number-literal-format".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "object-literal-sort-keys".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "origin-ordered-imports".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-conditional-expression".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-switch".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "typedef".
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "whitespace".

#### Reproduction
Before merge i updated tslint from 5.11.0 to 5.20.1
than i followed the instructions; https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration
Tried to migrate tslint to eslint on repo https://github.com/Azure/azure-iot-explorer

**Comment by KingDarBoja** [comment]
I will take a look at this, seems like either the merger is missing or something else 🤔
