### ISSUE TITLE
Missing Converter for no-dynamic-delete

### ISSUE THREAD

**Issue by rgant** [typescript-eslint/tslint-to-eslint-config#934]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 2.1.0
-   `typescript-eslint` version: 4.14.1

#### TSLint Rule Name

  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-dynamic-delete".

#### Package Source

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-dynamic-delete.md

**Comment by KingDarBoja** [comment]
TSLint Rule: https://palantir.github.io/tslint/rules/no-dynamic-delete/
