### ISSUE TITLE
Missing Converter for prefer-conditional-expression

### ISSUE THREAD

**Issue by rgant** [typescript-eslint/tslint-to-eslint-config#935]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 2.1.0
-   `typescript-eslint` version: 4.14.1

#### TSLint Rule Name

  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-conditional-expression".

#### Package Source

Not 100% sure this is a complete match, but the doc reads as close enough:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-ternary.md

**Comment by JoshuaKGoldberg** [comment]
Great catch, agreed! If there are some small differences they can always be output them as `notices`.

**Comment by KingDarBoja** [comment]
I am pretty sure that's the correct equivalent, although the roadmap is not up-to-date: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#functionality
