### ISSUE TITLE
Missing Converter for typedef

### ISSUE THREAD

**Issue by rgant** [typescript-eslint/tslint-to-eslint-config#937]
### 💥 Missing Converter

-   `tslint-to-eslint-config` version: 2.1.0
-   `typescript-eslint` version: 4.14.1

#### TSLint Rule Name

  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "typedef".

#### Package Source

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/typedef.md

**Comment by JoshuaKGoldberg** [comment]
Indeed! https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md also exists and, depending on the source TSLint `typedef` settings, should probably be used as the output rules.

**Comment by KingDarBoja** [comment]
The original rule at TSLint: https://palantir.github.io/tslint/rules/typedef/
