### ISSUE TITLE
Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by kinex** [typescript-eslint/tslint-to-eslint-config#952]
Command "npx tslint-to-eslint-config" gives me this error:
```
Error: EEXIST: file already exists, mkdir 'C:\Users\firstname'
command not found: tslint-to-eslint-config
```
Maybe the issue is related to my home folder path which contains spaces? It is something like "C:\Users\firstname lastname"

-   ESLint version: 7.20.0
-   Node version: 10.15.3

**Comment by JoshuaKGoldberg** [comment]
Hi @kinex, thanks for posting this! I'm on Windows right now and can't reproduce the error:

```
C:\Code\a b>npx tslint-to-eslint-config

✨ 57 rules replaced with their ESLint equivalents. ✨

...

✅ All is well! ✅

C:\Code\a b>
```

In general, having a home folder path containing spaces is risky. You might consider switching that to something short like `C:\Code`

**Comment by kinex** [comment]
Actually, I never created my home folder with that name :) It was Windows who did it without asking me, so now I have to live with that issue. I think the default behavior in Windows setup is that your home folder will be "c:\Users\firstname lastname" (not sure if you can change it during setup).

I have a feeling this issue is related to `npx` and not to `tslint-to-eslint-config` directly.

Anyway, I decided to port my lint configuration manually. It took only 30 minutes. Thanks!
